import Foundation

// MARK: - wb-01: Closed Guard Control

private let closedGuardControlQuestions: [Question] = [
    Question(id: "q-cg-01", unitId: "wb-01", format: .mcq2,
             prompt: "Your opponent tries to stand up from your closed guard. What should you do?",
             options: ["Break their posture down", "Open guard immediately"],
             correctAnswer: "Break their posture down",
             explanation: "Pull them forward to break posture before they base out and pass.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil,
             coachNote: "If they stand with your guard closed you risk a stack pass — break posture first."),
    Question(id: "q-cg-02", unitId: "wb-01", format: .mcq4,
             prompt: "Which grip best breaks your opponent's posture in closed guard?",
             options: ["Collar and sleeve", "Double collar", "Double underhooks on head", "Wrist control"],
             correctAnswer: "Double collar",
             explanation: "Double collar grips let you pull the head down and break posture efficiently.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-03", unitId: "wb-01", format: .trueFalse,
             prompt: "Squeezing your knees together in closed guard gives you more control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Closed knees remove space for your opponent to posture up.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-04", unitId: "wb-01", format: .mcq4,
             prompt: "What is the PRIMARY goal of closed guard?",
             options: ["Defend and stall", "Wait for your opponent to tire", "Control distance and threaten attacks", "Rest your legs"],
             correctAnswer: "Control distance and threaten attacks",
             explanation: "Closed guard is an offensive position — break posture, attack submissions, set up sweeps.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil,
             coachNote: "A passive closed guard gets passed. Stay active — create threats from every position."),
    Question(id: "q-cg-05", unitId: "wb-01", format: .trueFalse,
             prompt: "You should keep your guard closed when your opponent stands up completely.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Holding closed guard while they stand risks a guard pass. Open and adapt.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil,
             coachNote: "When they stand, open guard and play open guard or pull them back down."),
    Question(id: "q-cg-06", unitId: "wb-01", format: .mcq2,
             prompt: "Your opponent posts both hands on your hips to create distance. Best response?",
             options: ["Pull their elbows in and break posture", "Open guard and scoot away"],
             correctAnswer: "Pull their elbows in and break posture",
             explanation: "Removing their base by collapsing the elbows shuts down the posture attempt.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-07", unitId: "wb-01", format: .fillBlank,
             prompt: "Break their ___ before threatening submissions from closed guard.",
             options: ["posture", "hooks", "grip", "base"],
             correctAnswer: "posture",
             explanation: "Without breaking posture, your opponent is too upright to submit.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil,
             coachNote: "Remember: posture first, then attack. You can't choke someone sitting tall."),
    Question(id: "q-cg-08", unitId: "wb-01", format: .trueFalse,
             prompt: "In closed guard, your hips should be flat on the mat for best control.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Keeping your hips active and off the mat lets you angle for attacks and break posture.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-02: Closed Guard Attacks

private let closedGuardAttackQuestions: [Question] = [
    Question(id: "q-cga-01", unitId: "wb-02", format: .mcq4,
             prompt: "To set up a triangle from closed guard, you must first:",
             options: ["Open your guard wide", "Break posture and isolate one arm outside your legs", "Grab their ankle", "Stand up"],
             correctAnswer: "Break posture and isolate one arm outside your legs",
             explanation: "One arm in, one arm out creates the triangle angle.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Triangle fails when both arms are inside your legs — break posture and push one out."),
    Question(id: "q-cga-02", unitId: "wb-02", format: .trueFalse,
             prompt: "You can effectively attack with an armbar from closed guard without breaking posture first.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "A posted opponent resists the armbar easily. Break posture to remove their base.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cga-03", unitId: "wb-02", format: .mcq2,
             prompt: "Which movement creates the angle needed for a triangle choke from guard?",
             options: ["Hip escape (shrimp) to the side", "Bridging straight up"],
             correctAnswer: "Hip escape (shrimp) to the side",
             explanation: "Shrimping creates the angle to swing a leg over the shoulder.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cga-04", unitId: "wb-02", format: .fillBlank,
             prompt: "For the triangle from guard, you must isolate one ___ inside your legs.",
             options: ["arm", "leg", "head", "shoulder"],
             correctAnswer: "arm",
             explanation: "One arm in, one arm out — the classic triangle setup.",
             tags: ["guard", "submissions"], difficulty: 1, sceneImageName: nil,
             coachNote: "Both arms inside? Your triangle is weak. Push one arm across and lock."),
    Question(id: "q-cga-05", unitId: "wb-02", format: .mcq4,
             prompt: "For the hip bump sweep, you push off your hand and rotate toward which direction?",
             options: ["Away from your far arm", "Straight up", "Toward the same side as your posting arm", "Back down to the mat"],
             correctAnswer: "Toward the same side as your posting arm",
             explanation: "You post with one arm and hip bump into that same side to off-balance them.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cga-06", unitId: "wb-02", format: .trueFalse,
             prompt: "The scissor sweep works best when your opponent is sitting back in a low base.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Scissor sweep works best when they are upright — a low base resists the sweep.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil,
             coachNote: "Pull them forward first to raise their base before attempting the scissor sweep."),
    Question(id: "q-cga-07", unitId: "wb-02", format: .mcq2,
             prompt: "What is the key ingredient that opens all submission attacks from closed guard?",
             options: ["Breaking their posture", "Opening your legs wide"],
             correctAnswer: "Breaking their posture",
             explanation: "Broken posture creates proximity and removes their base — essential for every guard attack.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cga-08", unitId: "wb-02", format: .fillBlank,
             prompt: "The ___ sweep uses one leg to push the hip while pulling the arm to off-balance the opponent.",
             options: ["scissor", "hip bump", "tripod", "flower"],
             correctAnswer: "scissor",
             explanation: "Scissor sweep: one leg cuts the hip, the other pushes the shoulder.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-03: Guard Passing

private let guardPassingQuestions: [Question] = [
    Question(id: "q-gp-01", unitId: "wb-03", format: .mcq4,
             prompt: "When passing closed guard from knees, where should your elbows be?",
             options: ["Wide for balance", "On the mat beside you", "Tight to their hips", "Grabbing their belt"],
             correctAnswer: "Tight to their hips",
             explanation: "Tight elbows prevent the opponent from getting underhooks or arm drags.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil,
             coachNote: "Elbows flared = underhook gift. Keep them glued to their hips."),
    Question(id: "q-gp-02", unitId: "wb-03", format: .trueFalse,
             prompt: "Standing up is always the safest way to pass closed guard.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Standing can be effective but is risky — sweeps and leg locks become available.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-gp-03", unitId: "wb-03", format: .mcq2,
             prompt: "Your opponent attempts a hip bump sweep from closed guard. What stops it?",
             options: ["Post your hand on the mat behind you", "Squeeze your knees tighter"],
             correctAnswer: "Post your hand on the mat behind you",
             explanation: "A hand post behind you removes the base they need to complete the sweep.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-gp-04", unitId: "wb-03", format: .mcq4,
             prompt: "Which technique does NOT effectively open closed guard?",
             options: ["Stand and drive knee to tailbone", "Elbow to knee pressure", "Grab one ankle and push", "Grab their belt and pull up"],
             correctAnswer: "Grab their belt and pull up",
             explanation: "Grabbing the belt doesn't create the hip pressure needed to open the guard.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil,
             coachNote: "Focus on hip pressure downward — not pulling up. That's what opens the guard."),
    Question(id: "q-gp-05", unitId: "wb-03", format: .trueFalse,
             prompt: "When passing guard, getting one knee free is enough — you don't need to control both hips.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Controlling both hips prevents the guard from re-closing and limits sweep attempts.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-gp-06", unitId: "wb-03", format: .mcq2,
             prompt: "You are about to complete a guard pass but your opponent grabs your sleeve. Priority?",
             options: ["Clear the grip before passing", "Ignore it and rush the pass"],
             correctAnswer: "Clear the grip before passing",
             explanation: "Uncleared grips give your opponent handles to re-guard or sweep mid-pass.",
             tags: ["guard", "passing"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-gp-07", unitId: "wb-03", format: .fillBlank,
             prompt: "The toreando pass controls both ___ to pin the legs open and walk around.",
             options: ["ankles", "knees", "hips", "thighs"],
             correctAnswer: "ankles",
             explanation: "Gripping both ankles in the toreando lets you redirect the legs and pass around.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil,
             coachNote: "Don't muscle the toreando — use hip movement and angles, not arm strength."),
    Question(id: "q-gp-08", unitId: "wb-03", format: .trueFalse,
             prompt: "After passing the guard, you should immediately go for a submission.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Establish and consolidate your position first — secure the pass before attacking.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil),
]

// MARK: - wb-04: Side Control Top

private let sideControlTopQuestions: [Question] = [
    Question(id: "q-sc-01", unitId: "wb-04", format: .mcq4,
             prompt: "In side control, where should your hips be to apply maximum pressure?",
             options: ["High and away from opponent", "Low and heavy across their torso", "Perpendicular at their waist", "Stacked on their legs"],
             correctAnswer: "Low and heavy across their torso",
             explanation: "Low hips add pressure and make it hard for the opponent to bridge or roll.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil,
             coachNote: "Think of your hips as your weight anchor — keep them low and heavy across their chest."),
    Question(id: "q-sc-02", unitId: "wb-04", format: .trueFalse,
             prompt: "Cross-face pressure in side control helps flatten your opponent.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Cross-face turns the head and disconnects the opponent's hip-shoulder alignment.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sc-03", unitId: "wb-04", format: .mcq2,
             prompt: "Your opponent tries to escape side control by pushing your head. Best response?",
             options: ["Swim under their arm for underhook", "Back away and re-establish"],
             correctAnswer: "Swim under their arm for underhook",
             explanation: "Swimming under creates underhook control and maintains the position.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-04", unitId: "wb-04", format: .mcq4,
             prompt: "Which submission is most directly available from standard side control?",
             options: ["Rear naked choke", "Heel hook", "Kimura on the near arm", "Triangle from guard"],
             correctAnswer: "Kimura on the near arm",
             explanation: "Kimura is directly available from side control when the opponent's arm is exposed.",
             tags: ["side control", "submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "The near arm kimura — if they push your hip, give them the kimura."),
    Question(id: "q-sc-05", unitId: "wb-04", format: .trueFalse,
             prompt: "The 'north-south' position is a variant of side control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "North-south is side control rotated 180° — head near opponent's hips.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-06", unitId: "wb-04", format: .mcq2,
             prompt: "Your opponent bridges strongly to escape side control. To counter, you should:",
             options: ["Go with the roll and take mount", "Post your leg out and stay flat"],
             correctAnswer: "Go with the roll and take mount",
             explanation: "Following the bridge and taking mount is the reward for reading the escape.",
             tags: ["side control"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-sc-07", unitId: "wb-04", format: .fillBlank,
             prompt: "Use a ___ to turn your opponent's head away and flatten them in side control.",
             options: ["cross-face", "collar grip", "knee shield", "underhook"],
             correctAnswer: "cross-face",
             explanation: "Cross-face disconnects shoulder and hip alignment, preventing a bridge.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil,
             coachNote: "No cross-face? They can turn into you easily. Always establish it first."),
    Question(id: "q-sc-08", unitId: "wb-04", format: .trueFalse,
             prompt: "In side control, distributing your weight on both knees reduces your pressure on the opponent.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "To maximize pressure, drive your weight through your chest and hips, not knees.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-05: Side Control Escape

private let sideControlEscapeQuestions: [Question] = [
    Question(id: "q-sce-01", unitId: "wb-05", format: .mcq4,
             prompt: "What is the first step to begin escaping from side control?",
             options: ["Immediately bridge hard", "Create frames with your arms against their neck and hip", "Grab their leg", "Turn away from them"],
             correctAnswer: "Create frames with your arms against their neck and hip",
             explanation: "Frames create space and stop your opponent from flattening you completely.",
             tags: ["side control", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Frames first — without space you can't move. Elbow to hip, forearm to neck."),
    Question(id: "q-sce-02", unitId: "wb-05", format: .trueFalse,
             prompt: "You should shrimp (hip escape) before establishing frames when escaping side control.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Frames create the space that makes shrimping possible. Frame first, then shrimp.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sce-03", unitId: "wb-05", format: .mcq2,
             prompt: "When shrimping to recover guard from side control, your hips move:",
             options: ["Away from the opponent (toward their feet)", "Toward the opponent's head"],
             correctAnswer: "Away from the opponent (toward their feet)",
             explanation: "Shrimping away creates the space to bring your knee inside and re-guard.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sce-04", unitId: "wb-05", format: .fillBlank,
             prompt: "Bridge and ___ to create the space needed to escape side control.",
             options: ["shrimp", "roll", "push", "sit up"],
             correctAnswer: "shrimp",
             explanation: "The bridge-shrimp combination is the fundamental side control escape movement.",
             tags: ["side control", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Small shrimps beat big ones — precise hip movement beats muscling out."),
    Question(id: "q-sce-05", unitId: "wb-05", format: .mcq4,
             prompt: "When framing against side control, where does your bottom forearm go?",
             options: ["Across their throat", "On their hip", "Under their arm", "Against their knee"],
             correctAnswer: "On their hip",
             explanation: "Hip frame stops them from advancing while your top arm handles their upper body.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sce-06", unitId: "wb-05", format: .trueFalse,
             prompt: "Turning into your opponent from bottom side control is a valid escape direction.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Turning into them allows you to shoot for a single leg or take the turtle position.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil,
             coachNote: "Two options: turn away (re-guard) or turn in (single leg/turtle). Both work."),
    Question(id: "q-sce-07", unitId: "wb-05", format: .mcq2,
             prompt: "You recover half guard from side control. Your opponent quickly flattens you. You should:",
             options: ["Use your underhook to fight back to full guard or a sweep", "Immediately try to stand up"],
             correctAnswer: "Use your underhook to fight back to full guard or a sweep",
             explanation: "Underhook from half guard is the key tool — use it to create movement.",
             tags: ["side control", "escapes"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-sce-08", unitId: "wb-05", format: .fillBlank,
             prompt: "The ___ escape from side control involves bridging and spinning to face the opponent.",
             options: ["granby", "upa", "elbow-knee", "sit-out"],
             correctAnswer: "granby",
             explanation: "The granby roll uses a bridge and spin to face the opponent or recover guard.",
             tags: ["side control", "escapes"], difficulty: 3, sceneImageName: nil),
]

// MARK: - wb-06: Mount Control

private let mountControlQuestions: [Question] = [
    Question(id: "q-mc-01", unitId: "wb-06", format: .mcq4,
             prompt: "Your opponent bridges (upa) to escape mount. What is the best counter?",
             options: ["Squeeze your knees tighter", "Post your arm out and follow the roll", "Lean forward with all weight", "Grab their collar"],
             correctAnswer: "Post your arm out and follow the roll",
             explanation: "Posting stops the bridge. Following the roll lets you retake mount from the other side.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil,
             coachNote: "When they bridge, don't resist — post out and flow over. Fighting the bridge tires you out."),
    Question(id: "q-mc-02", unitId: "wb-06", format: .trueFalse,
             prompt: "High mount (near the armpits) gives you better control than low mount.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "High mount limits arm movement and opens more submission opportunities.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mc-03", unitId: "wb-06", format: .trueFalse,
             prompt: "Keeping your heels hooked under your opponent's legs in mount makes escape harder.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Hooks under the legs limit bridging power and prevent the elbow-knee escape.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-mc-04", unitId: "wb-06", format: .mcq2,
             prompt: "Your opponent gets their elbow to their knee and starts shrimping out. You should:",
             options: ["Follow their hips and re-establish mount", "Abandon mount and take side control"],
             correctAnswer: "Follow their hips and re-establish mount",
             explanation: "Staying active and following the hips is the key to keeping mount.",
             tags: ["mount"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-mc-05", unitId: "wb-06", format: .mcq4,
             prompt: "Which mount detail best prevents your opponent from turning to face you?",
             options: ["Grabbing their wrists", "Grapevining their legs", "Cross-face pressure on their neck", "Sitting up tall"],
             correctAnswer: "Cross-face pressure on their neck",
             explanation: "Cross-face in mount blocks the turn just as in side control — head controls the body.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil,
             coachNote: "Mount + cross-face = very hard to escape. This is your highest value detail."),
    Question(id: "q-mc-06", unitId: "wb-06", format: .trueFalse,
             prompt: "Leaning forward in mount transfers more weight onto your opponent and increases pressure.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Leaning forward shifts your center of gravity onto their chest and lungs.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mc-07", unitId: "wb-06", format: .fillBlank,
             prompt: "In mount, keep your ___ low to add pressure and make bridging difficult.",
             options: ["hips", "shoulders", "knees", "elbows"],
             correctAnswer: "hips",
             explanation: "Low hips maximize pressure and limit the opponent's ability to bridge.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil,
             coachNote: "Hips low = heavy mount. Hips high = light mount. Heaviness wins matches."),
    Question(id: "q-mc-08", unitId: "wb-06", format: .mcq4,
             prompt: "Compared to mount, knee-on-belly is better for:",
             options: ["Long-term pressure", "Preventing all escapes", "Mobility and quick transitions", "Rear choke setups"],
             correctAnswer: "Mobility and quick transitions",
             explanation: "Knee-on-belly is a transitional position — good for transitions but less stable than mount.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-07: Mount Escape

private let mountEscapeQuestions: [Question] = [
    Question(id: "q-me-01", unitId: "wb-07", format: .mcq2,
             prompt: "Which mount escape uses a bridge and rotation to roll the top person over?",
             options: ["Upa escape", "Elbow-knee escape"],
             correctAnswer: "Upa escape",
             explanation: "Upa uses bridging force and trapping an arm and leg to roll.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Upa works best when they are in low mount. In high mount, use elbow-knee."),
    Question(id: "q-me-02", unitId: "wb-07", format: .mcq4,
             prompt: "The elbow-knee escape from mount is designed to:",
             options: ["Submit the opponent with a triangle", "Roll them over your head", "Recover half guard or full guard", "Take their back"],
             correctAnswer: "Recover half guard or full guard",
             explanation: "Elbow-knee escape shrimps to create space and re-guard.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-me-03", unitId: "wb-07", format: .mcq4,
             prompt: "Before executing the upa escape, you must first:",
             options: ["Create frames and push them off", "Trap their arm and leg on the same side", "Sit up and grab their collar", "Turn toward them"],
             correctAnswer: "Trap their arm and leg on the same side",
             explanation: "Trapping the arm and leg gives you the fulcrum to complete the bridge-and-roll.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil,
             coachNote: "No trap = no upa. Their posted arm stops the roll. Trap it first every time."),
    Question(id: "q-me-04", unitId: "wb-07", format: .trueFalse,
             prompt: "Shrimping creates the space needed to execute the elbow-knee escape from mount.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Shrimping hips to one side creates the gap to insert your knee and recover guard.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-me-05", unitId: "wb-07", format: .mcq2,
             prompt: "When should you prefer the upa over the elbow-knee escape?",
             options: ["When opponent is in low mount with their weight forward", "When opponent is in high mount near your armpits"],
             correctAnswer: "When opponent is in low mount with their weight forward",
             explanation: "Forward weight makes the bridge more effective. High mount closes off the rolling space.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-me-06", unitId: "wb-07", format: .fillBlank,
             prompt: "In the upa escape, trap their ___ before bridging to complete the roll.",
             options: ["arm and leg", "head and neck", "hips", "belt"],
             correctAnswer: "arm and leg",
             explanation: "Trapping arm and leg on the same side is the setup for a successful upa roll.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Same-side trap is the key — arm and leg on the same side, then bridge explosively."),
    Question(id: "q-me-07", unitId: "wb-07", format: .mcq4,
             prompt: "After bridging in the upa escape, where do you continue to roll?",
             options: ["Back down to where you started", "To the same side as the trapped arm and leg", "Straight up", "Toward their legs"],
             correctAnswer: "To the same side as the trapped arm and leg",
             explanation: "You roll over the trapped side — that's the path of least resistance.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-me-08", unitId: "wb-07", format: .trueFalse,
             prompt: "The upa escape becomes harder when your opponent is in high mount near your armpits.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "High mount tightens the position and makes bridging and trapping more difficult.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-08: Back Control

private let backControlQuestions: [Question] = [
    Question(id: "q-bc-01", unitId: "wb-08", format: .mcq4,
             prompt: "When you have back control, where should your hooks be?",
             options: ["Behind their knees", "On their ankles", "Inside their thighs", "Outside their hips"],
             correctAnswer: "Inside their thighs",
             explanation: "Inside hooks on the thighs keep you attached and limit hip mobility.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil,
             coachNote: "Inside hooks = control. Outside hooks can be kicked off easily."),
    Question(id: "q-bc-02", unitId: "wb-08", format: .trueFalse,
             prompt: "You must maintain at least one hook to keep back control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Losing both hooks lets the opponent escape or roll out of back control.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-03", unitId: "wb-08", format: .mcq2,
             prompt: "When setting up the rear naked choke, what must you establish first?",
             options: ["Seatbelt grip (over-under around torso)", "Choking arm directly under chin"],
             correctAnswer: "Seatbelt grip (over-under around torso)",
             explanation: "Seatbelt control establishes position and prevents the opponent turning.",
             tags: ["back control", "submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "No seatbelt = they can turn and escape. Seatbelt first, then go for the choke."),
    Question(id: "q-bc-04", unitId: "wb-08", format: .mcq4,
             prompt: "To escape back control, which direction should you move toward?",
             options: ["Away from both arms", "Toward the choking arm side", "Straight forward", "Toward the non-choking arm side"],
             correctAnswer: "Toward the choking arm side",
             explanation: "Moving toward the choking arm side lets you work to face the opponent.",
             tags: ["back control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-05", unitId: "wb-08", format: .trueFalse,
             prompt: "A body triangle is a stronger control than two hooks from the back.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "The body triangle locks the hips completely and is very hard to escape.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-06", unitId: "wb-08", format: .mcq2,
             prompt: "Your opponent grabs your choking wrist to defend the RNC. You should:",
             options: ["Switch to a collar choke or bow-and-arrow", "Keep pulling the same arm harder"],
             correctAnswer: "Switch to a collar choke or bow-and-arrow",
             explanation: "Switching attacks prevents stalling and exploits their defensive focus.",
             tags: ["back control", "submissions"], difficulty: 3, sceneImageName: nil,
             coachNote: "When they defend the RNC, switch — don't muscle through. Their defense opens another attack."),
    Question(id: "q-bc-07", unitId: "wb-08", format: .fillBlank,
             prompt: "Keep your back control position by staying ___ to their body like a backpack.",
             options: ["tight", "loose", "square", "low"],
             correctAnswer: "tight",
             explanation: "Staying tight prevents space that allows them to turn or slide out.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-08", unitId: "wb-08", format: .trueFalse,
             prompt: "From the back, it is safer to have the opponent on their side rather than flat on their back.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "On their back they can steer your hooks off — on their side you have more control.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil,
             coachNote: "Angle matters: on their side gives you better hook control and choke access."),
]

// MARK: - wb-09: Submissions

private let submissionQuestions: [Question] = [
    Question(id: "q-sub-01", unitId: "wb-09", format: .mcq4,
             prompt: "When applying an armbar from mount, the correct position is:",
             options: ["Thumbs down, pull to chest", "Both hands on the wrist, push away", "Thumbs up, hips thrust up", "Wrists crossed, pull down"],
             correctAnswer: "Thumbs up, hips thrust up",
             explanation: "Thumb up rotates the elbow into position. Hips thrust apply the extension force.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Thumb up = elbow faces down = armbar works. Thumb down = no torque."),
    Question(id: "q-sub-02", unitId: "wb-09", format: .trueFalse,
             prompt: "A triangle choke works by compressing the carotid arteries, not the airway.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Blood chokes cut off blood to the brain — faster and more effective than air chokes.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-03", unitId: "wb-09", format: .mcq2,
             prompt: "The kimura grip is: one hand on their wrist, the other hand...",
             options: ["Gripping your own wrist (figure-four)", "On their bicep"],
             correctAnswer: "Gripping your own wrist (figure-four)",
             explanation: "Kimura = figure-four: wrist with one hand, grip your own wrist with the other.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Figure-four grip is the key — without it you just have a wrist grip, not a kimura."),
    Question(id: "q-sub-04", unitId: "wb-09", format: .mcq4,
             prompt: "When is it appropriate to tap in training?",
             options: ["Only when you are about to be knocked out", "Only if you have no way to escape", "Whenever a submission is applied and you feel it working", "Never — tapping is giving up"],
             correctAnswer: "Whenever a submission is applied and you feel it working",
             explanation: "Tapping early protects you from injury and is a sign of good training culture.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-05", unitId: "wb-09", format: .trueFalse,
             prompt: "The rear naked choke requires you to lock your hands together to be effective.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "The RNC uses one arm to choke and the other to push the head — no hand lock needed.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Interlocking hands in RNC is weaker — use the palm-to-bicep squeeze instead."),
    Question(id: "q-sub-06", unitId: "wb-09", format: .mcq2,
             prompt: "Your opponent clasps their hands to defend your armbar. Best response?",
             options: ["Break the grip by extending one arm and rotating", "Pull both arms toward you simultaneously"],
             correctAnswer: "Break the grip by extending one arm and rotating",
             explanation: "Rotating one arm breaks the grip structure more efficiently than pulling straight.",
             tags: ["submissions"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-sub-07", unitId: "wb-09", format: .fillBlank,
             prompt: "To finish a triangle choke, pull the head ___ and squeeze your knees together.",
             options: ["down", "sideways", "up", "back"],
             correctAnswer: "down",
             explanation: "Pulling the head down tightens the triangle and increases carotid compression.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Head down + knees squeeze = tap. Missing either makes the triangle loose."),
    Question(id: "q-sub-08", unitId: "wb-09", format: .trueFalse,
             prompt: "Finishing an armbar requires you to control the opponent's wrist, not just the arm.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Wrist control ensures the elbow stays aligned for maximum extension force.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-10: Takedowns

private let takedownQuestions: [Question] = [
    Question(id: "q-td-01", unitId: "wb-10", format: .mcq4,
             prompt: "In a single-leg takedown, the key finish movement after securing the leg is:",
             options: ["Pull straight back", "Run the pipe (step outside and cut)", "Jump on top", "Lift straight up"],
             correctAnswer: "Run the pipe (step outside and cut)",
             explanation: "Stepping outside cuts the angle and drops your weight through the leg.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil,
             coachNote: "Drive your shoulder into the thigh and step outside — don't just pull back."),
    Question(id: "q-td-02", unitId: "wb-10", format: .trueFalse,
             prompt: "In wrestling, a 'sprawl' is used to defend against a double-leg shot.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Sprawling drives your hips back and down to stuff the shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-td-03", unitId: "wb-10", format: .mcq2,
             prompt: "The double-leg takedown requires you to:",
             options: ["Change levels and shoot low", "Stay tall and grab both wrists"],
             correctAnswer: "Change levels and shoot low",
             explanation: "Level change drops below the opponent's center of gravity for the shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil,
             coachNote: "Level change is everything — stay tall and you'll bounce off. Drop low and shoot."),
    Question(id: "q-td-04", unitId: "wb-10", format: .mcq4,
             prompt: "After a successful takedown, your immediate priority is:",
             options: ["Go for a submission immediately", "Stand back up", "Establish top position control", "Call for a time-out"],
             correctAnswer: "Establish top position control",
             explanation: "Secure position first — rushing submissions from bad position loses them.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-05", unitId: "wb-10", format: .trueFalse,
             prompt: "Pulling guard counts as a takedown in competition BJJ.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Pulling guard gives 2 takedown points to the opponent.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil,
             coachNote: "Pulling guard surrenders points — if you want points, fight for the takedown."),
    Question(id: "q-td-06", unitId: "wb-10", format: .mcq2,
             prompt: "Your opponent has a collar-and-elbow grip. You want to shoot. First:",
             options: ["Break their grips before shooting", "Shoot immediately before they react"],
             correctAnswer: "Break their grips before shooting",
             explanation: "Shooting with grips intact lets them sprawl or redirect your momentum.",
             tags: ["takedowns"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-td-07", unitId: "wb-10", format: .fillBlank,
             prompt: "A ___ sprawl stops the double-leg shot by driving hips back and down.",
             options: ["defensive", "reactive", "front", "hip"],
             correctAnswer: "defensive",
             explanation: "The defensive sprawl counters the shot by removing your hips from their reach.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil,
             coachNote: "Sprawl early — waiting until they grab your legs is too late."),
    Question(id: "q-td-08", unitId: "wb-10", format: .trueFalse,
             prompt: "In standup, maintaining inside position on your opponent's arms gives you control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Inside position prevents their attacks and sets up your own entries.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-bt1: Stripe 1 Test (2 questions per unit = 20 total)

private let beltTestQuestions: [Question] = [
    // wb-01 Closed Guard Control
    Question(id: "bt-cg-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "What is the PRIMARY goal of closed guard?",
             options: ["Defend and stall", "Wait for your opponent to tire", "Control distance and threaten attacks", "Rest your legs"],
             correctAnswer: "Control distance and threaten attacks",
             explanation: "Closed guard is an offensive position — break posture, attack submissions, set up sweeps.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-cg-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "Squeezing your knees together in closed guard gives you more control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Closed knees remove space for your opponent to posture up.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    // wb-02 Closed Guard Attacks
    Question(id: "bt-cga-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "To set up a triangle from closed guard, you must first:",
             options: ["Open your guard wide", "Break posture and isolate one arm outside your legs", "Grab their ankle", "Stand up"],
             correctAnswer: "Break posture and isolate one arm outside your legs",
             explanation: "One arm in, one arm out creates the triangle angle.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "bt-cga-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "The scissor sweep works best when your opponent is sitting back in a low base.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Scissor sweep works best when they are upright — a low base resists the sweep.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil),
    // wb-03 Guard Passing
    Question(id: "bt-gp-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "When passing closed guard from knees, where should your elbows be?",
             options: ["Wide for balance", "On the mat beside you", "Tight to their hips", "Grabbing their belt"],
             correctAnswer: "Tight to their hips",
             explanation: "Tight elbows prevent the opponent from getting underhooks or arm drags.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-gp-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "After passing the guard, you should immediately go for a submission.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Establish and consolidate your position first.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil),
    // wb-04 Side Control Top
    Question(id: "bt-sc-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "In side control, where should your hips be to apply maximum pressure?",
             options: ["High and away from opponent", "Low and heavy across their torso", "Perpendicular at their waist", "Stacked on their legs"],
             correctAnswer: "Low and heavy across their torso",
             explanation: "Low hips add pressure and make it hard for the opponent to bridge or roll.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-sc-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "Cross-face pressure in side control helps flatten your opponent.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Cross-face turns the head and disconnects the opponent's hip-shoulder alignment.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    // wb-05 Side Control Escape
    Question(id: "bt-sce-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "What is the first step to begin escaping from side control?",
             options: ["Immediately bridge hard", "Create frames with your arms against their neck and hip", "Grab their leg", "Turn away from them"],
             correctAnswer: "Create frames with your arms against their neck and hip",
             explanation: "Frames create space and stop your opponent from flattening you completely.",
             tags: ["side control", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-sce-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "You should shrimp before establishing frames when escaping side control.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Frames create the space that makes shrimping possible. Frame first, then shrimp.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    // wb-06 Mount Control
    Question(id: "bt-mc-01", unitId: "wb-bt1", format: .trueFalse,
             prompt: "High mount (near the armpits) gives you better control than low mount.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "High mount limits arm movement and opens more submission opportunities.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-mc-02", unitId: "wb-bt1", format: .mcq4,
             prompt: "In mount, which detail best prevents your opponent from turning to face you?",
             options: ["Grabbing their wrists", "Grapevining their legs", "Cross-face pressure on their neck", "Sitting up tall"],
             correctAnswer: "Cross-face pressure on their neck",
             explanation: "Cross-face in mount blocks the turn — head controls the body.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
    // wb-07 Mount Escape
    Question(id: "bt-me-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "Before executing the upa escape, you must first:",
             options: ["Create frames and push them off", "Trap their arm and leg on the same side", "Sit up and grab their collar", "Turn toward them"],
             correctAnswer: "Trap their arm and leg on the same side",
             explanation: "Trapping the arm and leg gives you the fulcrum to complete the bridge-and-roll.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "bt-me-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "Shrimping creates the space needed to execute the elbow-knee escape from mount.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Shrimping hips to one side creates the gap to insert your knee and recover guard.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil),
    // wb-08 Back Control
    Question(id: "bt-bc-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "When you have back control, where should your hooks be?",
             options: ["Behind their knees", "On their ankles", "Inside their thighs", "Outside their hips"],
             correctAnswer: "Inside their thighs",
             explanation: "Inside hooks on the thighs keep you attached and limit hip mobility.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-bc-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "A body triangle is a stronger control than two hooks from the back.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "The body triangle locks the hips completely and is very hard to escape.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil),
    // wb-09 Submissions
    Question(id: "bt-sub-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "When is it appropriate to tap in training?",
             options: ["Only when you are about to be knocked out", "Only if you have no way to escape", "Whenever a submission is applied and you feel it working", "Never — tapping is giving up"],
             correctAnswer: "Whenever a submission is applied and you feel it working",
             explanation: "Tapping early protects you from injury and is a sign of good training culture.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-sub-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "A triangle choke works by compressing the carotid arteries, not the airway.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Blood chokes cut off blood to the brain — faster and more effective than air chokes.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    // wb-10 Takedowns
    Question(id: "bt-td-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "After a successful takedown, your immediate priority is:",
             options: ["Go for a submission immediately", "Stand back up", "Establish top position control", "Call for a time-out"],
             correctAnswer: "Establish top position control",
             explanation: "Secure position first — rushing submissions from bad position loses them.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "bt-td-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "In wrestling, a sprawl is used to defend against a double-leg shot.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Sprawling drives your hips back and down to stuff the shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
]

// MARK: - Units

extension Unit {
    static let whitebelt_en: [Unit] = [
        Unit(id: "wb-01", belt: .white, orderIndex: 0,
             title: "Closed Guard Control", description: "Control the closed guard and break posture",
             tags: ["guard"], isLocked: false, isCompleted: false, kind: .lesson,
             questions: closedGuardControlQuestions,
             coachIntro: "Closed guard is your first weapon. The key is breaking their posture — a tall opponent is impossible to submit. Pull their head down, keep your knees tight, and stay active."),
        Unit(id: "wb-02", belt: .white, orderIndex: 1,
             title: "Closed Guard Attacks", description: "Sweeps and submissions from closed guard",
             tags: ["guard", "sweeps", "submissions"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: closedGuardAttackQuestions,
             coachIntro: "Attacks flow from a broken posture. Triangle, armbar, hip bump sweep — they all start the same way. Break their base first, then pick your attack."),
        Unit(id: "wb-03", belt: .white, orderIndex: 2,
             title: "Guard Passing", description: "Break and pass the closed guard",
             tags: ["guard", "passing"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: guardPassingQuestions,
             coachIntro: "Passing guard requires patience and pressure. Keep your elbows tight, control their hips, and never rush the pass before clearing their grips."),
        Unit(id: "wb-04", belt: .white, orderIndex: 3,
             title: "Side Control Top", description: "Maintain and dominate from side control",
             tags: ["side control"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: sideControlTopQuestions,
             coachIntro: "Side control is all about weight and angles. Hips low, cross-face on, and follow every escape attempt. Heavy pressure makes their job exhausting."),
        Unit(id: "wb-05", belt: .white, orderIndex: 4,
             title: "Side Control Escape", description: "Recover guard from side control",
             tags: ["side control", "escapes"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: sideControlEscapeQuestions,
             coachIntro: "Escaping side control starts with frames — create space before you move. Bridge and shrimp is your best friend. Stay calm and be patient."),
        Unit(id: "wb-06", belt: .white, orderIndex: 5,
             title: "Mount Control", description: "Maintain and advance from mount",
             tags: ["mount"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: mountControlQuestions,
             coachIntro: "Mount is your highest value ground position. Low hips, cross-face, follow their escapes — do these three things and they can't get out."),
        Unit(id: "wb-07", belt: .white, orderIndex: 6,
             title: "Mount Escape", description: "Escape from the bottom of mount",
             tags: ["mount", "escapes"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: mountEscapeQuestions,
             coachIntro: "Two tools: upa (bridge and roll) and elbow-knee (shrimp to guard). Learn which to use when — and always trap before you bridge."),
        Unit(id: "wb-08", belt: .white, orderIndex: 7,
             title: "Back Control", description: "Take and keep the back",
             tags: ["back control"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: backControlQuestions,
             coachIntro: "The back is the most dominant position in BJJ. Hooks inside, seatbelt tight, and stay attached like a backpack. The RNC is always your first threat."),
        Unit(id: "wb-09", belt: .white, orderIndex: 8,
             title: "Submissions", description: "Basic submissions from dominant positions",
             tags: ["submissions"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: submissionQuestions,
             coachIntro: "Submissions only work from controlled positions. Position first, then submission. Triangle, armbar, kimura, RNC — master these four as a white belt."),
        Unit(id: "wb-10", belt: .white, orderIndex: 9,
             title: "Takedowns", description: "Get the fight to the ground",
             tags: ["takedowns"], isLocked: true, isCompleted: false, kind: .lesson,
             questions: takedownQuestions,
             coachIntro: "Two shots to learn first: double-leg and single-leg. Level change, penetration step, drive through. And learn the sprawl — you'll need it every class."),
        Unit(id: "wb-bt1", belt: .white, orderIndex: 10,
             title: "Stripe 1 Test", description: "Prove your White Belt foundations",
             tags: [], isLocked: true, isCompleted: false, kind: .beltTest,
             questions: beltTestQuestions,
             coachIntro: nil),
    ]
}
