import Foundation

// MARK: - Preguntas en Español

private let guardiaCerradaPreguntas: [Question] = [
    Question(id: "q-cg-01", unitId: "wb-01", format: .mcq2,
             prompt: "Tu oponente intenta levantarse desde tu guardia cerrada. ¿Qué debes hacer?",
             options: ["Romper su postura hacia abajo", "Abrir la guardia inmediatamente"],
             correctAnswer: "Romper su postura hacia abajo",
             explanation: "Jálalo hacia adelante para romper su postura antes de que base y pase.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-02", unitId: "wb-01", format: .mcq4,
             prompt: "¿Qué agarre rompe mejor la postura del oponente en guardia cerrada?",
             options: ["Cuello y manga", "Doble cuello", "Doble underhooks en la cabeza", "Control de muñeca"],
             correctAnswer: "Doble cuello",
             explanation: "Los agarres de doble cuello permiten jalar la cabeza hacia abajo y romper la postura eficientemente.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-03", unitId: "wb-01", format: .trueFalse,
             prompt: "Apretando las rodillas en guardia cerrada tienes más control.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "Las rodillas cerradas eliminan el espacio para que el oponente se incorpore.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-04", unitId: "wb-01", format: .mcq4,
             prompt: "¿Cuál es el objetivo PRINCIPAL de la guardia cerrada?",
             options: ["Defender y ganar tiempo", "Esperar a que el oponente se canse", "Controlar la distancia y amenazar con ataques", "Descansar las piernas"],
             correctAnswer: "Controlar la distancia y amenazar con ataques",
             explanation: "La guardia cerrada es una posición ofensiva — rompe la postura, ataca sumisiones, prepara barridas.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-05", unitId: "wb-01", format: .trueFalse,
             prompt: "Debes mantener la guardia cerrada cuando el oponente se levanta completamente.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Falso",
             explanation: "Mantener la guardia cerrada mientras se paran arriesga que pasen. Abre y adáptate.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-06", unitId: "wb-01", format: .mcq2,
             prompt: "Tu oponente apoya ambas manos en tus caderas para crear distancia. ¿Mejor respuesta?",
             options: ["Jala sus codos hacia adentro y rompe su postura", "Abre la guardia y aléjate"],
             correctAnswer: "Jala sus codos hacia adentro y rompe su postura",
             explanation: "Colapsar los codos elimina su base y detiene el intento de postura.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
]

private let escapadaGuardiaPreguntas: [Question] = [
    Question(id: "q-ge-01", unitId: "wb-02", format: .mcq4,
             prompt: "Al pasar la guardia cerrada desde rodillas, ¿dónde deben estar tus codos?",
             options: ["Abiertos para equilibrio", "En el tapete a tu lado", "Pegados a sus caderas", "Agarrando su cinturón"],
             correctAnswer: "Pegados a sus caderas",
             explanation: "Los codos pegados evitan que el oponente consiga underhooks o arm drags.",
             tags: ["guard", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-ge-02", unitId: "wb-02", format: .trueFalse,
             prompt: "Levantarse siempre es la forma más segura de pasar la guardia cerrada.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Falso",
             explanation: "Pararse puede ser efectivo pero arriesgado — barridas y llaves de pierna quedan disponibles.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-03", unitId: "wb-02", format: .mcq2,
             prompt: "Tu oponente intenta una barrida de cadera desde guardia cerrada. ¿Qué la detiene?",
             options: ["Apoya tu mano en el tapete detrás de ti", "Aprieta más las rodillas"],
             correctAnswer: "Apoya tu mano en el tapete detrás de ti",
             explanation: "Un apoyo detrás elimina la base que necesitan para completar la barrida.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-04", unitId: "wb-02", format: .mcq4,
             prompt: "¿Cuál NO es una técnica válida para abrir la guardia cerrada?",
             options: ["Pararse y presionar la rodilla al coxis", "Presión codo-rodilla", "Agarrar un tobillo y empujar", "Agarrar su cinturón y jalar hacia arriba"],
             correctAnswer: "Agarrar su cinturón y jalar hacia arriba",
             explanation: "Agarrar el cinturón no crea la presión de cadera necesaria para abrir la guardia.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-05", unitId: "wb-02", format: .trueFalse,
             prompt: "Al pasar la guardia, liberar una rodilla es suficiente — no necesitas controlar ambas caderas.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Falso",
             explanation: "Controlar ambas caderas evita que la guardia se cierre y limita intentos de barrida.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-06", unitId: "wb-02", format: .mcq2,
             prompt: "Estás a punto de pasar la guardia. Tu oponente agarra tu manga. Prioridad:",
             options: ["Limpiar el agarre antes de pasar", "Ignorarlo y apresurarte con el pase"],
             correctAnswer: "Limpiar el agarre antes de pasar",
             explanation: "Los agarres sin limpiar le dan manijas para re-guardar o barrer a mitad del pase.",
             tags: ["guard", "escapes"], difficulty: 3, sceneImageName: nil),
]

private let controlLateralPreguntas: [Question] = [
    Question(id: "q-sc-01", unitId: "wb-03", format: .mcq4,
             prompt: "En control lateral, ¿dónde deben estar tus caderas para máxima presión?",
             options: ["Altas y alejadas del oponente", "Bajas y pesadas sobre su torso", "Perpendiculares a su cintura", "Apiladas sobre sus piernas"],
             correctAnswer: "Bajas y pesadas sobre su torso",
             explanation: "Las caderas bajas añaden presión y dificultan que el oponente haga puente o ruede.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sc-02", unitId: "wb-03", format: .trueFalse,
             prompt: "La presión de cross-face en control lateral ayuda a aplanar al oponente.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "El cross-face gira la cabeza y desconecta la alineación cadera-hombro del oponente.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sc-03", unitId: "wb-03", format: .mcq2,
             prompt: "Tu oponente intenta escapar el control lateral empujando tu cabeza. ¿Mejor respuesta?",
             options: ["Nada por debajo de su brazo para underhook", "Retroceder y reestablecer"],
             correctAnswer: "Nada por debajo de su brazo para underhook",
             explanation: "Nadar hacia abajo crea control de underhook y mantiene la posición.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-04", unitId: "wb-03", format: .mcq4,
             prompt: "¿Qué sumisión está más disponible directamente desde el control lateral estándar?",
             options: ["Estrangulamiento trasero", "Heel hook", "Kimura en el brazo cercano", "Triángulo desde guardia"],
             correctAnswer: "Kimura en el brazo cercano",
             explanation: "La kimura está directamente disponible desde control lateral cuando el brazo del oponente está expuesto.",
             tags: ["side control", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-05", unitId: "wb-03", format: .trueFalse,
             prompt: "La posición 'norte-sur' es una variante del control lateral.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "Norte-sur es control lateral girado 180° — cabeza cerca de las caderas del oponente.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-06", unitId: "wb-03", format: .mcq2,
             prompt: "Tu oponente hace un puente fuerte para escapar el control lateral. Para contrarrestar:",
             options: ["Seguir el roleo y tomar la montada", "Apoyar la pierna y quedarte plano"],
             correctAnswer: "Seguir el roleo y tomar la montada",
             explanation: "Seguir el puente y tomar la montada es la recompensa por leer la escapada.",
             tags: ["side control"], difficulty: 3, sceneImageName: nil),
]

private let montadaPreguntas: [Question] = [
    Question(id: "q-mt-01", unitId: "wb-04", format: .mcq4,
             prompt: "Tu oponente hace upa (puente) para escapar la montada. ¿Cuál es el mejor contra?",
             options: ["Aprieta más las rodillas", "Apoya el brazo para base y síguelo", "Inclínate hacia adelante con todo el peso", "Agarra su cuello"],
             correctAnswer: "Apoya el brazo para base y síguelo",
             explanation: "El apoyo detiene el puente. Seguir el roleo te permite tomar la montada del otro lado.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mt-02", unitId: "wb-04", format: .trueFalse,
             prompt: "La montada alta (cerca de las axilas) da mejor control que la montada baja.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "La montada alta limita el movimiento de los brazos y abre más oportunidades de sumisión.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mt-03", unitId: "wb-04", format: .mcq2,
             prompt: "¿Qué escapada de montada usa un puente y rotación para voltear al de arriba?",
             options: ["Escapada upa", "Escapada codo-rodilla"],
             correctAnswer: "Escapada upa",
             explanation: "Upa usa fuerza de puente y una trampa en el brazo/pierna para rolear.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mt-04", unitId: "wb-04", format: .mcq4,
             prompt: "La escapada codo-rodilla desde la montada está diseñada para:",
             options: ["Someter al oponente con un triángulo", "Rolarlo sobre tu cabeza", "Recuperar media guardia o guardia completa", "Tomar su espalda"],
             correctAnswer: "Recuperar media guardia o guardia completa",
             explanation: "La escapada codo-rodilla hace camarón para crear espacio y recuperar guardia.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-mt-05", unitId: "wb-04", format: .trueFalse,
             prompt: "En montada, mantener los talones ganchados bajo las piernas del oponente dificulta su escapada.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "Los ganchos bajo las piernas limitan el poder del puente y previenen la escapada codo-rodilla.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-mt-06", unitId: "wb-04", format: .mcq2,
             prompt: "Tu oponente lleva su codo a la rodilla y empieza a hacer camarón. Debes:",
             options: ["Seguir sus caderas y reestablecer la montada", "Abandonar la montada e ir al control lateral"],
             correctAnswer: "Seguir sus caderas y reestablecer la montada",
             explanation: "Mantenerse activo y seguir las caderas es clave para mantener la montada.",
             tags: ["mount"], difficulty: 3, sceneImageName: nil),
]

private let controlEspaldaPreguntas: [Question] = [
    Question(id: "q-bc-01", unitId: "wb-05", format: .mcq4,
             prompt: "Cuando tienes control de espalda, ¿dónde deben estar tus ganchos?",
             options: ["Detrás de sus rodillas", "En sus tobillos", "Por dentro de sus muslos", "Por fuera de sus caderas"],
             correctAnswer: "Por dentro de sus muslos",
             explanation: "Los ganchos interiores en los muslos te mantienen pegado y limitan la movilidad de cadera.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-02", unitId: "wb-05", format: .trueFalse,
             prompt: "Debes mantener al menos un gancho para conservar el control de espalda.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "Perder ambos ganchos permite al oponente escapar o rodar fuera del control de espalda.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-03", unitId: "wb-05", format: .mcq2,
             prompt: "Al preparar el estrangulamiento trasero, ¿qué debes establecer primero?",
             options: ["Agarre cinturón de seguridad (sobre-bajo alrededor del torso)", "Brazo estrangulador directamente bajo el mentón"],
             correctAnswer: "Agarre cinturón de seguridad (sobre-bajo alrededor del torso)",
             explanation: "El control cinturón establece posición y evita que el oponente gire.",
             tags: ["back control", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-04", unitId: "wb-05", format: .mcq4,
             prompt: "Para escapar el control de espalda, ¿hacia qué dirección debes moverte?",
             options: ["Lejos de ambos brazos", "Hacia el lado del brazo estrangulador", "Directo hacia adelante", "Hacia el lado del brazo no estrangulador"],
             correctAnswer: "Hacia el lado del brazo estrangulador",
             explanation: "Moverse hacia el lado del brazo estrangulador te permite trabajar para enfrentar al oponente.",
             tags: ["back control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-05", unitId: "wb-05", format: .trueFalse,
             prompt: "El triángulo de cuerpo es un control más fuerte que dos ganchos desde la espalda.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "El triángulo de cuerpo bloquea completamente las caderas y es muy difícil de escapar.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-06", unitId: "wb-05", format: .mcq2,
             prompt: "Tu oponente agarra tu muñeca estranguladora para defender el RNC. Debes:",
             options: ["Cambiar a bow-and-arrow o estrangulamiento de cuello", "Seguir jalando el mismo brazo con más fuerza"],
             correctAnswer: "Cambiar a bow-and-arrow o estrangulamiento de cuello",
             explanation: "Cambiar de ataque evita el estancamiento y explota el enfoque defensivo del oponente.",
             tags: ["back control", "submissions"], difficulty: 3, sceneImageName: nil),
]

private let sumisionesPreguntas: [Question] = [
    Question(id: "q-sub-01", unitId: "wb-06", format: .mcq4,
             prompt: "Al aplicar un armbar desde la montada, la posición correcta es:",
             options: ["Pulgares abajo, jalar al pecho", "Ambas manos en la muñeca, empujar lejos", "Pulgares arriba, caderas hacia arriba", "Muñecas cruzadas, jalar abajo"],
             correctAnswer: "Pulgares arriba, caderas hacia arriba",
             explanation: "Pulgares arriba rota el codo a posición. El thrust de caderas aplica la fuerza de extensión.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sub-02", unitId: "wb-06", format: .trueFalse,
             prompt: "El triángulo funciona comprimiendo las arterias carótidas, no la vía aérea.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "Los estrangulamiento de sangre cortan el flujo al cerebro — más rápidos que los de aire.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-03", unitId: "wb-06", format: .mcq2,
             prompt: "El agarre kimura es: una mano en su muñeca, la otra mano...",
             options: ["Agarrando tu propia muñeca (figura cuatro)", "En su bícep"],
             correctAnswer: "Agarrando tu propia muñeca (figura cuatro)",
             explanation: "Kimura = figura cuatro: muñeca con una mano, agarra tu propia muñeca con la otra.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sub-04", unitId: "wb-06", format: .mcq4,
             prompt: "¿Cuándo es apropiado rendirse (tap) en el entrenamiento?",
             options: ["Solo si estás a punto de perder el conocimiento", "Solo si no hay forma de escapar", "Cuando se aplica una sumisión y la sientes funcionar", "Nunca — rendirse es darse por vencido"],
             correctAnswer: "Cuando se aplica una sumisión y la sientes funcionar",
             explanation: "Rendirse temprano te protege de lesiones y es señal de buena cultura de entrenamiento.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-05", unitId: "wb-06", format: .trueFalse,
             prompt: "El estrangulamiento trasero requiere que juntes las manos para ser efectivo.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Falso",
             explanation: "El RNC usa un agarre 'rear naked' — un brazo estrangula, el otro aplica presión en la cabeza.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sub-06", unitId: "wb-06", format: .mcq2,
             prompt: "Tienes un armbar pero tu oponente junta las manos para defender. ¿Mejor respuesta?",
             options: ["Rompe su agarre extendiendo un brazo y rotando", "Jala ambos brazos hacia ti simultáneamente"],
             correctAnswer: "Rompe su agarre extendiendo un brazo y rotando",
             explanation: "Rotar un brazo rompe la estructura del agarre más eficientemente que jalar directo.",
             tags: ["submissions"], difficulty: 3, sceneImageName: nil),
]

private let derribosPreguntas: [Question] = [
    Question(id: "q-td-01", unitId: "wb-07", format: .mcq4,
             prompt: "En un derribo de pierna simple, el movimiento clave para terminar es:",
             options: ["Jalar directo hacia atrás", "Correr el tubo (salir afuera y cortar)", "Saltar encima", "Levantar directo hacia arriba"],
             correctAnswer: "Correr el tubo (salir afuera y cortar)",
             explanation: "Salir afuera corta el ángulo y deja caer tu peso a través de la pierna.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-02", unitId: "wb-07", format: .trueFalse,
             prompt: "En lucha, un 'sprawl' se usa para defender contra un shot de doble pierna.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Verdadero",
             explanation: "El sprawl lleva tus caderas hacia atrás y abajo para bloquear el shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-td-03", unitId: "wb-07", format: .mcq2,
             prompt: "El derribo de doble pierna requiere que:",
             options: ["Cambies de nivel y dispares bajo", "Te quedes alto y agarres ambas muñecas"],
             correctAnswer: "Cambies de nivel y dispares bajo",
             explanation: "El cambio de nivel baja por debajo del centro de gravedad del oponente para el shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-td-04", unitId: "wb-07", format: .mcq4,
             prompt: "Después de un derribo exitoso, tu prioridad inmediata es:",
             options: ["Ir inmediatamente por una sumisión", "Volverte a parar", "Establecer control de posición superior", "Llamar a tiempo"],
             correctAnswer: "Establecer control de posición superior",
             explanation: "Asegura la posición primero — apresurarse con sumisiones desde mala posición las pierde.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-05", unitId: "wb-07", format: .trueFalse,
             prompt: "Jalar la guardia cuenta como derribo en la competición de BJJ.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "Falso",
             explanation: "Jalar la guardia cede los puntos de derribo (2 pts) al oponente.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-06", unitId: "wb-07", format: .mcq2,
             prompt: "Tu oponente tiene agarre cuello-codo en standup. Quieres disparar. Primero:",
             options: ["Limpia sus agarres antes de disparar", "Dispara inmediatamente antes de que reaccione"],
             correctAnswer: "Limpia sus agarres antes de disparar",
             explanation: "Disparar con sus agarres intactos les permite sprawlear o redirigir tu momentum.",
             tags: ["takedowns"], difficulty: 3, sceneImageName: nil),
]

private let examenFranjaPreguntasES: [Question] = {
    let all = guardiaCerradaPreguntas + escapadaGuardiaPreguntas + controlLateralPreguntas
        + montadaPreguntas + controlEspaldaPreguntas + sumisionesPreguntas + derribosPreguntas
    return all.map { q in
        Question(id: "bt-\(q.id)", unitId: "wb-bt1",
                 format: q.format, prompt: q.prompt,
                 options: q.options, correctAnswer: q.correctAnswer,
                 explanation: q.explanation, tags: q.tags,
                 difficulty: q.difficulty, sceneImageName: nil)
    }
}()

// MARK: - Unidades en Español

extension Unit {
    static let whitebelt_es: [Unit] = [
        Unit(id: "wb-01", belt: .white, orderIndex: 0,
             title: "Guardia Cerrada", description: "Fundamentos del control en guardia cerrada",
             tags: ["guard"], isLocked: false, isCompleted: false, isBeltTest: false,
             questions: guardiaCerradaPreguntas),
        Unit(id: "wb-02", belt: .white, orderIndex: 1,
             title: "Escapar la Guardia", description: "Escapar de la guardia cerrada",
             tags: ["escapes", "guard"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: escapadaGuardiaPreguntas),
        Unit(id: "wb-03", belt: .white, orderIndex: 2,
             title: "Control Lateral", description: "Mantener el control lateral",
             tags: ["side control"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: controlLateralPreguntas),
        Unit(id: "wb-04", belt: .white, orderIndex: 3,
             title: "Montada", description: "Posición de montada y control",
             tags: ["mount"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: montadaPreguntas),
        Unit(id: "wb-05", belt: .white, orderIndex: 4,
             title: "Control de Espalda", description: "Tomar y mantener la espalda",
             tags: ["back control"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: controlEspaldaPreguntas),
        Unit(id: "wb-06", belt: .white, orderIndex: 5,
             title: "Sumisiones", description: "Sumisiones básicas desde posiciones dominantes",
             tags: ["submissions"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: sumisionesPreguntas),
        Unit(id: "wb-07", belt: .white, orderIndex: 6,
             title: "Derribos", description: "Llevar la pelea al suelo",
             tags: ["takedowns"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: derribosPreguntas),
        Unit(id: "wb-bt1", belt: .white, orderIndex: 7,
             title: "Examen Franja 1", description: "Demuestra tus fundamentos del Cinturón Blanco",
             tags: [], isLocked: true, isCompleted: false, isBeltTest: true,
             questions: examenFranjaPreguntasES),
    ]
}
