import Foundation

// MARK: - wb-01: Control de Guardia Cerrada

private let guardiaCerradaControlPreguntas: [Question] = [
    Question(id: "q-cg-01", unitId: "wb-01", format: .mcq2,
             prompt: "Tu oponente intenta levantarse desde tu guardia cerrada. ¿Qué debes hacer?",
             options: ["Romper su postura hacia abajo", "Abrir la guardia inmediatamente"],
             correctAnswer: "Romper su postura hacia abajo",
             explanation: "Jálalo hacia adelante para romper su postura antes de que base y pase.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil,
             coachNote: "Si se paran con la guardia cerrada arriesgas un pase de stack — rompe la postura primero."),
    Question(id: "q-cg-02", unitId: "wb-01", format: .mcq4,
             prompt: "¿Qué agarre rompe mejor la postura del oponente en guardia cerrada?",
             options: ["Cuello y manga", "Doble cuello", "Doble underhooks en la cabeza", "Control de muñeca"],
             correctAnswer: "Doble cuello",
             explanation: "Los agarres de doble cuello permiten jalar la cabeza hacia abajo y romper la postura eficientemente.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-03", unitId: "wb-01", format: .trueFalse,
             prompt: "Apretando las rodillas en guardia cerrada tienes más control.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Las rodillas cerradas eliminan el espacio para que el oponente se incorpore.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-04", unitId: "wb-01", format: .mcq4,
             prompt: "¿Cuál es el objetivo PRINCIPAL de la guardia cerrada?",
             options: ["Defender y ganar tiempo", "Esperar a que el oponente se canse", "Controlar la distancia y amenazar con ataques", "Descansar las piernas"],
             correctAnswer: "Controlar la distancia y amenazar con ataques",
             explanation: "La guardia cerrada es una posición ofensiva — rompe la postura, ataca sumisiones, prepara barridas.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil,
             coachNote: "Guardia pasiva se pasa. Mantente activo — crea amenazas desde cada posición."),
    Question(id: "q-cg-05", unitId: "wb-01", format: .trueFalse,
             prompt: "Debes mantener la guardia cerrada cuando el oponente se levanta completamente.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Mantener la guardia cerrada mientras se paran arriesga que pasen. Abre y adáptate.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil,
             coachNote: "Cuando se paran, abre la guardia y juega guardia abierta o jálalos de vuelta."),
    Question(id: "q-cg-06", unitId: "wb-01", format: .mcq2,
             prompt: "Tu oponente apoya ambas manos en tus caderas para crear distancia. ¿Mejor respuesta?",
             options: ["Jala sus codos hacia adentro y rompe su postura", "Abre la guardia y aléjate"],
             correctAnswer: "Jala sus codos hacia adentro y rompe su postura",
             explanation: "Colapsar los codos elimina su base y detiene el intento de postura.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-07", unitId: "wb-01", format: .fillBlank,
             prompt: "Rompe su ___ antes de amenazar con sumisiones desde guardia cerrada.",
             options: ["postura", "agarre", "base", "equilibrio"],
             correctAnswer: "postura",
             explanation: "Sin romper la postura, tu oponente está muy erguido para someter.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil,
             coachNote: "Recuerda: postura primero, luego ataca. No puedes estrangular a alguien sentado erguido."),
    Question(id: "q-cg-08", unitId: "wb-01", format: .trueFalse,
             prompt: "En guardia cerrada, tus caderas deben estar planas en el tapete para mejor control.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Mantener las caderas activas y fuera del tapete permite angularte para ataques.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-02: Ataques desde Guardia Cerrada

private let guardiaCerradaAtaquesPreguntas: [Question] = [
    Question(id: "q-cga-01", unitId: "wb-02", format: .mcq4,
             prompt: "Para preparar un triángulo desde guardia cerrada, primero debes:",
             options: ["Abrir tu guardia completamente", "Romper postura y aislar un brazo fuera de tus piernas", "Agarrar su tobillo", "Levantarte"],
             correctAnswer: "Romper postura y aislar un brazo fuera de tus piernas",
             explanation: "Un brazo adentro, uno afuera crea el ángulo del triángulo.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "El triángulo falla cuando ambos brazos están dentro de tus piernas — rompe postura y empuja uno afuera."),
    Question(id: "q-cga-02", unitId: "wb-02", format: .trueFalse,
             prompt: "Puedes atacar efectivamente con armbar desde guardia cerrada sin romper la postura primero.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Un oponente con postura resiste el armbar fácilmente. Rompe la postura para eliminar su base.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cga-03", unitId: "wb-02", format: .mcq2,
             prompt: "¿Qué movimiento crea el ángulo para el triángulo desde guardia?",
             options: ["Camarón (hip escape) hacia el lado", "Puente directo hacia arriba"],
             correctAnswer: "Camarón (hip escape) hacia el lado",
             explanation: "El camarón crea el ángulo para pasar una pierna sobre el hombro.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cga-04", unitId: "wb-02", format: .fillBlank,
             prompt: "Para el triángulo desde guardia, debes aislar un ___ dentro de tus piernas.",
             options: ["brazo", "pierna", "cabeza", "hombro"],
             correctAnswer: "brazo",
             explanation: "Un brazo adentro, uno afuera — la preparación clásica del triángulo.",
             tags: ["guard", "submissions"], difficulty: 1, sceneImageName: nil,
             coachNote: "¿Ambos brazos adentro? Tu triángulo es débil. Empuja un brazo al lado y cierra."),
    Question(id: "q-cga-05", unitId: "wb-02", format: .mcq4,
             prompt: "Para la barrida de cadera, te empujas con tu mano y rotas hacia:",
             options: ["Lejos de tu brazo lejano", "Directo hacia arriba", "Hacia el mismo lado del brazo de apoyo", "Hacia abajo al tapete"],
             correctAnswer: "Hacia el mismo lado del brazo de apoyo",
             explanation: "Apoyas con un brazo y golpeas de cadera hacia ese mismo lado para desequilibrarlos.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cga-06", unitId: "wb-02", format: .trueFalse,
             prompt: "La barrida de tijera funciona mejor cuando el oponente tiene base baja hacia atrás.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "La barrida de tijera funciona mejor cuando están erguidos — una base baja resiste la barrida.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil,
             coachNote: "Jálalos hacia adelante primero para elevar su base antes de intentar la barrida de tijera."),
    Question(id: "q-cga-07", unitId: "wb-02", format: .mcq2,
             prompt: "¿Qué ingrediente clave abre todos los ataques desde guardia cerrada?",
             options: ["Romper su postura", "Abrir las piernas completamente"],
             correctAnswer: "Romper su postura",
             explanation: "La postura rota crea proximidad y elimina su base — esencial para cada ataque de guardia.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cga-08", unitId: "wb-02", format: .fillBlank,
             prompt: "La barrida de ___ usa una pierna para empujar la cadera mientras jala el brazo.",
             options: ["tijera", "cadera", "trípode", "flor"],
             correctAnswer: "tijera",
             explanation: "Barrida de tijera: una pierna corta la cadera, la otra empuja el hombro.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-03: Pase de Guardia

private let paseGuardiaPreguntas: [Question] = [
    Question(id: "q-gp-01", unitId: "wb-03", format: .mcq4,
             prompt: "Al pasar la guardia cerrada desde rodillas, ¿dónde deben estar tus codos?",
             options: ["Abiertos para equilibrio", "En el tapete a tu lado", "Pegados a sus caderas", "Agarrando su cinturón"],
             correctAnswer: "Pegados a sus caderas",
             explanation: "Los codos pegados evitan que el oponente consiga underhooks o arm drags.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil,
             coachNote: "Codos abiertos = regalo de underhook. Mantenlos pegados a sus caderas."),
    Question(id: "q-gp-02", unitId: "wb-03", format: .trueFalse,
             prompt: "Levantarse siempre es la forma más segura de pasar la guardia cerrada.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Pararse puede ser efectivo pero arriesgado — barridas y llaves de pierna quedan disponibles.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-gp-03", unitId: "wb-03", format: .mcq2,
             prompt: "Tu oponente intenta una barrida de cadera desde guardia cerrada. ¿Qué la detiene?",
             options: ["Apoya tu mano en el tapete detrás de ti", "Aprieta más las rodillas"],
             correctAnswer: "Apoya tu mano en el tapete detrás de ti",
             explanation: "Un apoyo detrás elimina la base que necesitan para completar la barrida.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-gp-04", unitId: "wb-03", format: .mcq4,
             prompt: "¿Qué técnica NO abre efectivamente la guardia cerrada?",
             options: ["Pararse y presionar la rodilla al coxis", "Presión codo-rodilla", "Agarrar un tobillo y empujar", "Agarrar su cinturón y jalar hacia arriba"],
             correctAnswer: "Agarrar su cinturón y jalar hacia arriba",
             explanation: "Agarrar el cinturón no crea la presión de cadera necesaria para abrir la guardia.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil,
             coachNote: "Enfócate en presión de cadera hacia abajo — no jalar hacia arriba. Eso es lo que abre la guardia."),
    Question(id: "q-gp-05", unitId: "wb-03", format: .trueFalse,
             prompt: "Al pasar la guardia, liberar una rodilla es suficiente — no necesitas controlar ambas caderas.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Controlar ambas caderas evita que la guardia se cierre y limita intentos de barrida.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-gp-06", unitId: "wb-03", format: .mcq2,
             prompt: "Estás a punto de completar el pase pero tu oponente agarra tu manga. Prioridad:",
             options: ["Limpiar el agarre antes de pasar", "Ignorarlo y apresurarte con el pase"],
             correctAnswer: "Limpiar el agarre antes de pasar",
             explanation: "Los agarres sin limpiar le dan manijas para re-guardar o barrer a mitad del pase.",
             tags: ["guard", "passing"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-gp-07", unitId: "wb-03", format: .fillBlank,
             prompt: "El pase toreando controla ambos ___ para fijar las piernas abiertas y rodear.",
             options: ["tobillos", "rodillas", "caderas", "muslos"],
             correctAnswer: "tobillos",
             explanation: "Agarrar ambos tobillos en el toreando permite redirigir las piernas y pasar alrededor.",
             tags: ["guard", "passing"], difficulty: 2, sceneImageName: nil,
             coachNote: "No fuerces el toreando — usa movimiento de cadera y ángulos, no fuerza de brazos."),
    Question(id: "q-gp-08", unitId: "wb-03", format: .trueFalse,
             prompt: "Después de pasar la guardia, debes ir inmediatamente por una sumisión.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Primero establece y consolida tu posición — asegura el pase antes de atacar.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil),
]

// MARK: - wb-04: Control Lateral Superior

private let controlLateralSuperiorPreguntas: [Question] = [
    Question(id: "q-sc-01", unitId: "wb-04", format: .mcq4,
             prompt: "En control lateral, ¿dónde deben estar tus caderas para máxima presión?",
             options: ["Altas y alejadas del oponente", "Bajas y pesadas sobre su torso", "Perpendiculares a su cintura", "Apiladas sobre sus piernas"],
             correctAnswer: "Bajas y pesadas sobre su torso",
             explanation: "Las caderas bajas añaden presión y dificultan que el oponente haga puente o ruede.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil,
             coachNote: "Piensa en tus caderas como tu ancla de peso — mantenlas bajas y pesadas sobre su pecho."),
    Question(id: "q-sc-02", unitId: "wb-04", format: .trueFalse,
             prompt: "La presión de cross-face en control lateral ayuda a aplanar al oponente.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El cross-face gira la cabeza y desconecta la alineación cadera-hombro del oponente.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sc-03", unitId: "wb-04", format: .mcq2,
             prompt: "Tu oponente intenta escapar el control lateral empujando tu cabeza. ¿Mejor respuesta?",
             options: ["Nada por debajo de su brazo para underhook", "Retroceder y reestablecer"],
             correctAnswer: "Nada por debajo de su brazo para underhook",
             explanation: "Nadar hacia abajo crea control de underhook y mantiene la posición.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-04", unitId: "wb-04", format: .mcq4,
             prompt: "¿Qué sumisión está más disponible desde control lateral estándar?",
             options: ["Estrangulamiento trasero", "Heel hook", "Kimura en el brazo cercano", "Triángulo desde guardia"],
             correctAnswer: "Kimura en el brazo cercano",
             explanation: "La kimura está directamente disponible desde control lateral cuando el brazo del oponente está expuesto.",
             tags: ["side control", "submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "La kimura del brazo cercano — si empujan tu cadera, dales la kimura."),
    Question(id: "q-sc-05", unitId: "wb-04", format: .trueFalse,
             prompt: "La posición 'norte-sur' es una variante del control lateral.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Norte-sur es control lateral girado 180° — cabeza cerca de las caderas del oponente.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-06", unitId: "wb-04", format: .mcq2,
             prompt: "Tu oponente hace un puente fuerte para escapar el control lateral. Para contrarrestar:",
             options: ["Seguir el roleo y tomar la montada", "Apoyar la pierna y quedarte plano"],
             correctAnswer: "Seguir el roleo y tomar la montada",
             explanation: "Seguir el puente y tomar la montada es la recompensa por leer la escapada.",
             tags: ["side control"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-sc-07", unitId: "wb-04", format: .fillBlank,
             prompt: "Usa un ___ para girar la cabeza del oponente y aplastarlo en control lateral.",
             options: ["cross-face", "agarre de cuello", "escudo de rodilla", "underhook"],
             correctAnswer: "cross-face",
             explanation: "El cross-face desconecta la alineación hombro-cadera, previniendo el puente.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil,
             coachNote: "¿Sin cross-face? Pueden girarse hacia ti fácilmente. Establécelo siempre primero."),
    Question(id: "q-sc-08", unitId: "wb-04", format: .trueFalse,
             prompt: "En control lateral, distribuir el peso en ambas rodillas reduce tu presión sobre el oponente.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Para maximizar la presión, dirige tu peso a través del pecho y las caderas, no las rodillas.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-05: Escapar el Control Lateral

private let escaparControlLateralPreguntas: [Question] = [
    Question(id: "q-sce-01", unitId: "wb-05", format: .mcq4,
             prompt: "¿Cuál es el primer paso para escapar el control lateral?",
             options: ["Hacer puente fuerte inmediatamente", "Crear marcos con los brazos contra su cuello y cadera", "Agarrar su pierna", "Girarte lejos de él"],
             correctAnswer: "Crear marcos con los brazos contra su cuello y cadera",
             explanation: "Los marcos crean espacio y evitan que el oponente te aplaste completamente.",
             tags: ["side control", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Marcos primero — sin espacio no puedes moverte. Codo a cadera, antebrazo al cuello."),
    Question(id: "q-sce-02", unitId: "wb-05", format: .trueFalse,
             prompt: "Debes hacer camarón antes de establecer marcos al escapar el control lateral.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Los marcos crean el espacio que hace posible el camarón. Marco primero, luego camarón.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sce-03", unitId: "wb-05", format: .mcq2,
             prompt: "Al hacer camarón para recuperar guardia desde control lateral, tus caderas se mueven:",
             options: ["Lejos del oponente (hacia sus pies)", "Hacia la cabeza del oponente"],
             correctAnswer: "Lejos del oponente (hacia sus pies)",
             explanation: "El camarón lejos crea espacio para meter la rodilla adentro y recuperar guardia.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sce-04", unitId: "wb-05", format: .fillBlank,
             prompt: "Puente y ___ para crear el espacio necesario para escapar el control lateral.",
             options: ["camarón", "rodar", "empujar", "sentarse"],
             correctAnswer: "camarón",
             explanation: "La combinación puente-camarón es el movimiento fundamental de escape del control lateral.",
             tags: ["side control", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Camarones pequeños ganan a los grandes — el movimiento preciso de cadera supera la fuerza."),
    Question(id: "q-sce-05", unitId: "wb-05", format: .mcq4,
             prompt: "Al crear marcos contra el control lateral, ¿dónde va tu antebrazo inferior?",
             options: ["Cruzando su garganta", "En su cadera", "Bajo su brazo", "Contra su rodilla"],
             correctAnswer: "En su cadera",
             explanation: "El marco de cadera los detiene mientras el brazo superior maneja su cuerpo superior.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sce-06", unitId: "wb-05", format: .trueFalse,
             prompt: "Girarte hacia tu oponente desde abajo del control lateral es una dirección de escape válida.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Girarte hacia ellos permite entrar por una sola pierna o tomar posición tortuga.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil,
             coachNote: "Dos opciones: girarte lejos (recuperar guardia) o girarte hacia adentro (pierna simple/tortuga)."),
    Question(id: "q-sce-07", unitId: "wb-05", format: .mcq2,
             prompt: "Recuperas media guardia desde control lateral. Tu oponente te aplasta rápido. Debes:",
             options: ["Usar tu underhook para luchar hacia guardia completa o una barrida", "Intentar pararte inmediatamente"],
             correctAnswer: "Usar tu underhook para luchar hacia guardia completa o una barrida",
             explanation: "El underhook desde media guardia es la herramienta clave — úsalo para crear movimiento.",
             tags: ["side control", "escapes"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-sce-08", unitId: "wb-05", format: .fillBlank,
             prompt: "La escapada ___ del control lateral implica hacer puente y girar para enfrentar al oponente.",
             options: ["granby", "upa", "codo-rodilla", "salida"],
             correctAnswer: "granby",
             explanation: "El roleo granby usa un puente y giro para enfrentar al oponente o recuperar guardia.",
             tags: ["side control", "escapes"], difficulty: 3, sceneImageName: nil),
]

// MARK: - wb-06: Control desde Montada

private let controlMontadaPreguntas: [Question] = [
    Question(id: "q-mc-01", unitId: "wb-06", format: .mcq4,
             prompt: "Tu oponente hace upa (puente) para escapar la montada. ¿Cuál es el mejor contra?",
             options: ["Aprieta más las rodillas", "Apoya el brazo y sigue el roleo", "Inclínate hacia adelante con todo el peso", "Agarra su cuello"],
             correctAnswer: "Apoya el brazo y sigue el roleo",
             explanation: "El apoyo detiene el puente. Seguir el roleo te permite retomar la montada del otro lado.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil,
             coachNote: "Cuando hacen puente, no resistas — apoya y fluye. Pelear el puente te cansa."),
    Question(id: "q-mc-02", unitId: "wb-06", format: .trueFalse,
             prompt: "La montada alta (cerca de las axilas) da mejor control que la montada baja.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "La montada alta limita el movimiento de los brazos y abre más oportunidades de sumisión.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mc-03", unitId: "wb-06", format: .trueFalse,
             prompt: "Mantener los talones ganchados bajo las piernas del oponente en montada dificulta su escape.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Los ganchos bajo las piernas limitan el poder del puente y previenen la escapada codo-rodilla.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-mc-04", unitId: "wb-06", format: .mcq2,
             prompt: "Tu oponente lleva su codo a la rodilla y empieza a hacer camarón. Debes:",
             options: ["Seguir sus caderas y reestablecer la montada", "Abandonar la montada e ir al control lateral"],
             correctAnswer: "Seguir sus caderas y reestablecer la montada",
             explanation: "Mantenerse activo y seguir las caderas es clave para mantener la montada.",
             tags: ["mount"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-mc-05", unitId: "wb-06", format: .mcq4,
             prompt: "¿Qué detalle de montada evita mejor que tu oponente se gire hacia ti?",
             options: ["Agarrar sus muñecas", "Enganchar sus piernas", "Presión cross-face en su cuello", "Sentarte erguido"],
             correctAnswer: "Presión cross-face en su cuello",
             explanation: "El cross-face en montada bloquea el giro — la cabeza controla el cuerpo.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil,
             coachNote: "Montada + cross-face = muy difícil de escapar. Este es tu detalle de mayor valor."),
    Question(id: "q-mc-06", unitId: "wb-06", format: .trueFalse,
             prompt: "Inclinarte hacia adelante en montada transfiere más peso sobre el oponente y aumenta la presión.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Inclinarse hacia adelante desplaza tu centro de gravedad sobre su pecho y pulmones.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mc-07", unitId: "wb-06", format: .fillBlank,
             prompt: "En montada, mantén tus ___ bajas para añadir presión y dificultar el puente.",
             options: ["caderas", "hombros", "rodillas", "codos"],
             correctAnswer: "caderas",
             explanation: "Las caderas bajas maximizan la presión y limitan la capacidad del oponente de hacer puente.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil,
             coachNote: "Caderas bajas = montada pesada. Caderas altas = montada ligera. La pesadez gana."),
    Question(id: "q-mc-08", unitId: "wb-06", format: .mcq4,
             prompt: "Comparado con la montada, la rodilla al estómago es mejor para:",
             options: ["Presión a largo plazo", "Prevenir todas las escapadas", "Movilidad y transiciones rápidas", "Preparar estrangulamiento trasero"],
             correctAnswer: "Movilidad y transiciones rápidas",
             explanation: "La rodilla al estómago es una posición transitoria — buena para transiciones pero menos estable.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-07: Escapar la Montada

private let escaparMontadaPreguntas: [Question] = [
    Question(id: "q-me-01", unitId: "wb-07", format: .mcq2,
             prompt: "¿Qué escapada de montada usa un puente y rotación para voltear al de arriba?",
             options: ["Escapada upa", "Escapada codo-rodilla"],
             correctAnswer: "Escapada upa",
             explanation: "Upa usa fuerza de puente y una trampa en el brazo/pierna para rolear.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Upa funciona mejor en montada baja. En montada alta, usa codo-rodilla."),
    Question(id: "q-me-02", unitId: "wb-07", format: .mcq4,
             prompt: "La escapada codo-rodilla desde montada está diseñada para:",
             options: ["Someter al oponente con un triángulo", "Rolarlo sobre tu cabeza", "Recuperar media guardia o guardia completa", "Tomar su espalda"],
             correctAnswer: "Recuperar media guardia o guardia completa",
             explanation: "La escapada codo-rodilla hace camarón para crear espacio y recuperar guardia.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-me-03", unitId: "wb-07", format: .mcq4,
             prompt: "Antes de ejecutar la escapada upa, primero debes:",
             options: ["Crear marcos y empujarlos", "Atrapar su brazo y pierna del mismo lado", "Sentarte y agarrar su cuello", "Girarte hacia ellos"],
             correctAnswer: "Atrapar su brazo y pierna del mismo lado",
             explanation: "Atrapar el brazo y la pierna da el fulcro para completar el puente y roleo.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil,
             coachNote: "Sin trampa = sin upa. Su brazo apoyado detiene el roleo. Atrápalo siempre primero."),
    Question(id: "q-me-04", unitId: "wb-07", format: .trueFalse,
             prompt: "El camarón crea el espacio necesario para ejecutar la escapada codo-rodilla desde montada.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El camarón de cadera hacia un lado crea el espacio para insertar la rodilla y recuperar guardia.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-me-05", unitId: "wb-07", format: .mcq2,
             prompt: "¿Cuándo debes preferir el upa sobre la escapada codo-rodilla?",
             options: ["Cuando el oponente está en montada baja con peso hacia adelante", "Cuando está en montada alta cerca de tus axilas"],
             correctAnswer: "Cuando el oponente está en montada baja con peso hacia adelante",
             explanation: "El peso hacia adelante hace el puente más efectivo. La montada alta cierra el espacio de roleo.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-me-06", unitId: "wb-07", format: .fillBlank,
             prompt: "En la escapada upa, atrapa su ___ antes de hacer puente para completar el roleo.",
             options: ["brazo y pierna", "cabeza y cuello", "caderas", "cinturón"],
             correctAnswer: "brazo y pierna",
             explanation: "Atrapar brazo y pierna del mismo lado es la preparación para un roleo upa exitoso.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil,
             coachNote: "Trampa del mismo lado es la clave — brazo y pierna del mismo lado, luego puente explosivo."),
    Question(id: "q-me-07", unitId: "wb-07", format: .mcq4,
             prompt: "Después de hacer puente en la escapada upa, ¿hacia dónde continúas rodando?",
             options: ["Hacia donde empezaste", "Hacia el mismo lado del brazo y pierna atrapados", "Directo hacia arriba", "Hacia sus piernas"],
             correctAnswer: "Hacia el mismo lado del brazo y pierna atrapados",
             explanation: "Ruedas sobre el lado atrapado — ese es el camino de menor resistencia.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-me-08", unitId: "wb-07", format: .trueFalse,
             prompt: "La escapada upa se vuelve más difícil cuando tu oponente está en montada alta cerca de tus axilas.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "La montada alta aprieta la posición y hace el puente y la trampa más difíciles.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-08: Control de Espalda

private let controlEspaldaPreguntas: [Question] = [
    Question(id: "q-bc-01", unitId: "wb-08", format: .mcq4,
             prompt: "Cuando tienes control de espalda, ¿dónde deben estar tus ganchos?",
             options: ["Detrás de sus rodillas", "En sus tobillos", "Por dentro de sus muslos", "Por fuera de sus caderas"],
             correctAnswer: "Por dentro de sus muslos",
             explanation: "Los ganchos interiores en los muslos te mantienen pegado y limitan la movilidad de cadera.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil,
             coachNote: "Ganchos interiores = control. Los ganchos exteriores se pueden patear fácilmente."),
    Question(id: "q-bc-02", unitId: "wb-08", format: .trueFalse,
             prompt: "Debes mantener al menos un gancho para conservar el control de espalda.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Perder ambos ganchos permite al oponente escapar o rodar fuera del control de espalda.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-03", unitId: "wb-08", format: .mcq2,
             prompt: "Al preparar el estrangulamiento trasero, ¿qué debes establecer primero?",
             options: ["Agarre cinturón de seguridad (sobre-bajo alrededor del torso)", "Brazo estrangulador directamente bajo el mentón"],
             correctAnswer: "Agarre cinturón de seguridad (sobre-bajo alrededor del torso)",
             explanation: "El control cinturón establece posición y evita que el oponente gire.",
             tags: ["back control", "submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Sin cinturón = pueden girarse y escapar. Cinturón primero, luego el estrangulamiento."),
    Question(id: "q-bc-04", unitId: "wb-08", format: .mcq4,
             prompt: "Para escapar el control de espalda, ¿hacia qué dirección debes moverte?",
             options: ["Lejos de ambos brazos", "Hacia el lado del brazo estrangulador", "Directo hacia adelante", "Hacia el lado del brazo no estrangulador"],
             correctAnswer: "Hacia el lado del brazo estrangulador",
             explanation: "Moverse hacia el lado del brazo estrangulador te permite trabajar para enfrentar al oponente.",
             tags: ["back control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-05", unitId: "wb-08", format: .trueFalse,
             prompt: "El triángulo de cuerpo es un control más fuerte que dos ganchos desde la espalda.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El triángulo de cuerpo bloquea completamente las caderas y es muy difícil de escapar.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-06", unitId: "wb-08", format: .mcq2,
             prompt: "Tu oponente agarra tu muñeca estranguladora para defender el RNC. Debes:",
             options: ["Cambiar a estrangulamiento de cuello o bow-and-arrow", "Seguir jalando el mismo brazo con más fuerza"],
             correctAnswer: "Cambiar a estrangulamiento de cuello o bow-and-arrow",
             explanation: "Cambiar de ataque evita el estancamiento y explota el enfoque defensivo del oponente.",
             tags: ["back control", "submissions"], difficulty: 3, sceneImageName: nil,
             coachNote: "Cuando defienden el RNC, cambia — no lo forces. Su defensa abre otro ataque."),
    Question(id: "q-bc-07", unitId: "wb-08", format: .fillBlank,
             prompt: "Mantén tu control de espalda pegándote ___ a su cuerpo como una mochila.",
             options: ["apretado", "suelto", "cuadrado", "bajo"],
             correctAnswer: "apretado",
             explanation: "Mantenerse apretado evita el espacio que les permite girarse o deslizarse afuera.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-08", unitId: "wb-08", format: .trueFalse,
             prompt: "Desde la espalda, es más seguro tener al oponente de lado que plano boca arriba.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Boca arriba pueden dirigir tus ganchos afuera — de lado tienes mejor control.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil,
             coachNote: "El ángulo importa: de lado da mejor control de ganchos y acceso al estrangulamiento."),
]

// MARK: - wb-09: Sumisiones

private let sumisionesPreguntas: [Question] = [
    Question(id: "q-sub-01", unitId: "wb-09", format: .mcq4,
             prompt: "Al aplicar un armbar desde la montada, la posición correcta es:",
             options: ["Pulgares abajo, jalar al pecho", "Ambas manos en la muñeca, empujar lejos", "Pulgares arriba, caderas hacia arriba", "Muñecas cruzadas, jalar abajo"],
             correctAnswer: "Pulgares arriba, caderas hacia arriba",
             explanation: "Pulgares arriba rota el codo a posición. El thrust de caderas aplica la fuerza de extensión.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Pulgar arriba = codo hacia abajo = armbar funciona. Pulgar abajo = sin torque."),
    Question(id: "q-sub-02", unitId: "wb-09", format: .trueFalse,
             prompt: "El triángulo funciona comprimiendo las arterias carótidas, no la vía aérea.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Los estrangulamiento de sangre cortan el flujo al cerebro — más rápidos que los de aire.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-03", unitId: "wb-09", format: .mcq2,
             prompt: "El agarre kimura es: una mano en su muñeca, la otra mano...",
             options: ["Agarrando tu propia muñeca (figura cuatro)", "En su bícep"],
             correctAnswer: "Agarrando tu propia muñeca (figura cuatro)",
             explanation: "Kimura = figura cuatro: muñeca con una mano, agarra tu propia muñeca con la otra.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "El agarre figura cuatro es clave — sin él solo tienes agarre de muñeca, no kimura."),
    Question(id: "q-sub-04", unitId: "wb-09", format: .mcq4,
             prompt: "¿Cuándo es apropiado rendirse (tap) en el entrenamiento?",
             options: ["Solo si estás a punto de perder el conocimiento", "Solo si no hay forma de escapar", "Cuando se aplica una sumisión y la sientes funcionar", "Nunca — rendirse es darse por vencido"],
             correctAnswer: "Cuando se aplica una sumisión y la sientes funcionar",
             explanation: "Rendirse temprano te protege de lesiones y es señal de buena cultura de entrenamiento.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-05", unitId: "wb-09", format: .trueFalse,
             prompt: "El estrangulamiento trasero requiere que juntes las manos para ser efectivo.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "El RNC usa un brazo para estrangular y el otro para empujar la cabeza — sin juntar manos.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Juntar manos en RNC es más débil — usa el apriete palma al bícep."),
    Question(id: "q-sub-06", unitId: "wb-09", format: .mcq2,
             prompt: "Tu oponente junta las manos para defender tu armbar. ¿Mejor respuesta?",
             options: ["Rompe el agarre extendiendo un brazo y rotando", "Jala ambos brazos hacia ti simultáneamente"],
             correctAnswer: "Rompe el agarre extendiendo un brazo y rotando",
             explanation: "Rotar un brazo rompe la estructura del agarre más eficientemente que jalar directo.",
             tags: ["submissions"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-sub-07", unitId: "wb-09", format: .fillBlank,
             prompt: "Para terminar un triángulo, jala la cabeza ___ y aprieta las rodillas juntas.",
             options: ["abajo", "al lado", "arriba", "atrás"],
             correctAnswer: "abajo",
             explanation: "Jalar la cabeza hacia abajo aprieta el triángulo y aumenta la compresión de la carótida.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil,
             coachNote: "Cabeza abajo + rodillas apretadas = tap. Faltando cualquiera, el triángulo es flojo."),
    Question(id: "q-sub-08", unitId: "wb-09", format: .trueFalse,
             prompt: "Terminar un armbar requiere controlar la muñeca del oponente, no solo el brazo.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El control de muñeca asegura que el codo esté alineado para máxima fuerza de extensión.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-10: Derribos

private let derribosPreguntas: [Question] = [
    Question(id: "q-td-01", unitId: "wb-10", format: .mcq4,
             prompt: "En un derribo de pierna simple, el movimiento clave para terminar es:",
             options: ["Jalar directo hacia atrás", "Correr el tubo (salir afuera y cortar)", "Saltar encima", "Levantar directo hacia arriba"],
             correctAnswer: "Correr el tubo (salir afuera y cortar)",
             explanation: "Salir afuera corta el ángulo y deja caer tu peso a través de la pierna.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil,
             coachNote: "Empuja tu hombro contra el muslo y sal afuera — no solo jales hacia atrás."),
    Question(id: "q-td-02", unitId: "wb-10", format: .trueFalse,
             prompt: "En lucha, un 'sprawl' se usa para defender contra un shot de doble pierna.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El sprawl lleva tus caderas hacia atrás y abajo para bloquear el shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-td-03", unitId: "wb-10", format: .mcq2,
             prompt: "El derribo de doble pierna requiere que:",
             options: ["Cambies de nivel y dispares bajo", "Te quedes alto y agarres ambas muñecas"],
             correctAnswer: "Cambies de nivel y dispares bajo",
             explanation: "El cambio de nivel baja por debajo del centro de gravedad del oponente para el shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil,
             coachNote: "El cambio de nivel lo es todo — quedarte alto y rebotarás. Baja y dispara."),
    Question(id: "q-td-04", unitId: "wb-10", format: .mcq4,
             prompt: "Después de un derribo exitoso, tu prioridad inmediata es:",
             options: ["Ir inmediatamente por una sumisión", "Volverte a parar", "Establecer control de posición superior", "Llamar a tiempo"],
             correctAnswer: "Establecer control de posición superior",
             explanation: "Asegura la posición primero — apresurarse con sumisiones desde mala posición las pierde.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-05", unitId: "wb-10", format: .trueFalse,
             prompt: "Jalar la guardia cuenta como derribo en la competición de BJJ.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Jalar la guardia cede 2 puntos de derribo al oponente.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil,
             coachNote: "Jalar guardia cede puntos — si quieres puntos, pelea por el derribo."),
    Question(id: "q-td-06", unitId: "wb-10", format: .mcq2,
             prompt: "Tu oponente tiene agarre cuello-codo. Quieres disparar. Primero:",
             options: ["Limpia sus agarres antes de disparar", "Dispara inmediatamente antes de que reaccione"],
             correctAnswer: "Limpia sus agarres antes de disparar",
             explanation: "Disparar con sus agarres intactos les permite sprawlear o redirigir tu momentum.",
             tags: ["takedowns"], difficulty: 3, sceneImageName: nil),
    Question(id: "q-td-07", unitId: "wb-10", format: .fillBlank,
             prompt: "Un sprawl ___ detiene el shot de doble pierna llevando las caderas hacia atrás y abajo.",
             options: ["defensivo", "reactivo", "frontal", "de cadera"],
             correctAnswer: "defensivo",
             explanation: "El sprawl defensivo contrarresta el shot eliminando tus caderas de su alcance.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil,
             coachNote: "Sprawlea temprano — esperar hasta que te agarren las piernas es demasiado tarde."),
    Question(id: "q-td-08", unitId: "wb-10", format: .trueFalse,
             prompt: "En pie, mantener posición interior en los brazos del oponente te da control.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "La posición interior previene sus ataques y prepara tus propias entradas.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
]

// MARK: - wb-bt1: Examen Franja 1

private let examenFranjaPreguntasES: [Question] = [
    // wb-01
    Question(id: "bt-cg-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "¿Cuál es el objetivo PRINCIPAL de la guardia cerrada?",
             options: ["Defender y ganar tiempo", "Esperar a que el oponente se canse", "Controlar la distancia y amenazar con ataques", "Descansar las piernas"],
             correctAnswer: "Controlar la distancia y amenazar con ataques",
             explanation: "La guardia cerrada es una posición ofensiva.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-cg-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "Apretando las rodillas en guardia cerrada tienes más control.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Las rodillas cerradas eliminan el espacio para que el oponente se incorpore.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    // wb-02
    Question(id: "bt-cga-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "Para preparar un triángulo desde guardia cerrada, primero debes:",
             options: ["Abrir tu guardia completamente", "Romper postura y aislar un brazo fuera de tus piernas", "Agarrar su tobillo", "Levantarte"],
             correctAnswer: "Romper postura y aislar un brazo fuera de tus piernas",
             explanation: "Un brazo adentro, uno afuera crea el ángulo del triángulo.",
             tags: ["guard", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "bt-cga-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "La barrida de tijera funciona mejor cuando el oponente tiene base baja hacia atrás.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "La barrida de tijera funciona mejor cuando están erguidos.",
             tags: ["guard", "sweeps"], difficulty: 2, sceneImageName: nil),
    // wb-03
    Question(id: "bt-gp-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "Al pasar la guardia cerrada desde rodillas, ¿dónde deben estar tus codos?",
             options: ["Abiertos para equilibrio", "En el tapete a tu lado", "Pegados a sus caderas", "Agarrando su cinturón"],
             correctAnswer: "Pegados a sus caderas",
             explanation: "Los codos pegados evitan underhooks o arm drags.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-gp-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "Después de pasar la guardia, debes ir inmediatamente por una sumisión.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Primero establece y consolida tu posición.",
             tags: ["guard", "passing"], difficulty: 1, sceneImageName: nil),
    // wb-04
    Question(id: "bt-sc-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "En control lateral, ¿dónde deben estar tus caderas para máxima presión?",
             options: ["Altas y alejadas del oponente", "Bajas y pesadas sobre su torso", "Perpendiculares a su cintura", "Apiladas sobre sus piernas"],
             correctAnswer: "Bajas y pesadas sobre su torso",
             explanation: "Las caderas bajas añaden presión y dificultan el puente.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-sc-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "La presión de cross-face en control lateral ayuda a aplanar al oponente.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El cross-face gira la cabeza y desconecta la alineación del oponente.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    // wb-05
    Question(id: "bt-sce-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "¿Cuál es el primer paso para escapar el control lateral?",
             options: ["Hacer puente fuerte inmediatamente", "Crear marcos con los brazos", "Agarrar su pierna", "Girarte lejos de él"],
             correctAnswer: "Crear marcos con los brazos",
             explanation: "Los marcos crean espacio para que puedas moverte.",
             tags: ["side control", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-sce-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "Debes hacer camarón antes de establecer marcos al escapar el control lateral.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "False",
             explanation: "Los marcos crean el espacio que hace posible el camarón. Marco primero.",
             tags: ["side control", "escapes"], difficulty: 2, sceneImageName: nil),
    // wb-06
    Question(id: "bt-mc-01", unitId: "wb-bt1", format: .trueFalse,
             prompt: "La montada alta (cerca de las axilas) da mejor control que la montada baja.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "La montada alta limita el movimiento de los brazos.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-mc-02", unitId: "wb-bt1", format: .mcq4,
             prompt: "¿Qué detalle evita mejor que el oponente se gire hacia ti en montada?",
             options: ["Agarrar sus muñecas", "Enganchar sus piernas", "Presión cross-face en su cuello", "Sentarte erguido"],
             correctAnswer: "Presión cross-face en su cuello",
             explanation: "El cross-face en montada bloquea el giro.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
    // wb-07
    Question(id: "bt-me-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "Antes de ejecutar la escapada upa, primero debes:",
             options: ["Crear marcos y empujarlos", "Atrapar su brazo y pierna del mismo lado", "Sentarte y agarrar su cuello", "Girarte hacia ellos"],
             correctAnswer: "Atrapar su brazo y pierna del mismo lado",
             explanation: "Atrapar brazo y pierna da el fulcro para el roleo.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "bt-me-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "El camarón crea el espacio para la escapada codo-rodilla desde montada.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El camarón crea el espacio para insertar la rodilla.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil),
    // wb-08
    Question(id: "bt-bc-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "Cuando tienes control de espalda, ¿dónde deben estar tus ganchos?",
             options: ["Detrás de sus rodillas", "En sus tobillos", "Por dentro de sus muslos", "Por fuera de sus caderas"],
             correctAnswer: "Por dentro de sus muslos",
             explanation: "Los ganchos interiores te mantienen pegado y limitan la movilidad.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-bc-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "El triángulo de cuerpo es un control más fuerte que dos ganchos desde la espalda.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El triángulo de cuerpo bloquea completamente las caderas.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil),
    // wb-09
    Question(id: "bt-sub-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "¿Cuándo es apropiado rendirse (tap) en el entrenamiento?",
             options: ["Solo si estás a punto de perder el conocimiento", "Solo si no hay forma de escapar", "Cuando se aplica una sumisión y la sientes funcionar", "Nunca — rendirse es darse por vencido"],
             correctAnswer: "Cuando se aplica una sumisión y la sientes funcionar",
             explanation: "Rendirse temprano te protege de lesiones.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "bt-sub-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "El triángulo funciona comprimiendo las arterias carótidas, no la vía aérea.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "Los estrangulamiento de sangre cortan el flujo al cerebro.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    // wb-10
    Question(id: "bt-td-01", unitId: "wb-bt1", format: .mcq4,
             prompt: "Después de un derribo exitoso, tu prioridad inmediata es:",
             options: ["Ir inmediatamente por una sumisión", "Volverte a parar", "Establecer control de posición superior", "Llamar a tiempo"],
             correctAnswer: "Establecer control de posición superior",
             explanation: "Asegura la posición primero.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "bt-td-02", unitId: "wb-bt1", format: .trueFalse,
             prompt: "En lucha, un sprawl se usa para defender contra un shot de doble pierna.",
             options: ["Verdadero", "Falso"],
             correctAnswer: "True",
             explanation: "El sprawl lleva tus caderas hacia atrás y abajo para bloquear el shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
]

// MARK: - Unidades en Español

extension Unit {
    static let whitebelt_es: [Unit] = [

        // ── JUEGO DE GUARDIA ───────────────────────────────────────────────

        Unit(id: "wb-01-l1", belt: .white, orderIndex: 0,
             title: "Control de Guardia Cerrada", description: "Controla la guardia cerrada y rompe la postura",
             tags: ["guard"], isLocked: false, isCompleted: false,
             kind: .lesson,
             questions: Array(guardiaCerradaControlPreguntas[0..<4]),
             coachIntro: "La guardia cerrada es tu primera arma. Jala su cabeza abajo, mantén las rodillas apretadas.",
             sectionTitle: "Juego de Guardia",
             topicTitle: "Control de Guardia Cerrada",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-01-l2", belt: .white, orderIndex: 1,
             title: "Control de Guardia Cerrada", description: "Controla la guardia cerrada y rompe la postura",
             tags: ["guard"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(guardiaCerradaControlPreguntas[4..<8]),
             topicTitle: "Control de Guardia Cerrada",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-02-l1", belt: .white, orderIndex: 2,
             title: "Ataques desde Guardia Cerrada", description: "Barridas y sumisiones",
             tags: ["guard", "sweeps"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(guardiaCerradaAtaquesPreguntas[0..<4]),
             coachIntro: "Los ataques fluyen de una postura rota. Triángulo, armbar, barrida de cadera — todos empiezan igual.",
             topicTitle: "Ataques desde Guardia Cerrada",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-02-l2", belt: .white, orderIndex: 3,
             title: "Ataques desde Guardia Cerrada", description: "Barridas y sumisiones",
             tags: ["guard", "sweeps"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(guardiaCerradaAtaquesPreguntas[4..<8]),
             topicTitle: "Ataques desde Guardia Cerrada",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-cm-01", belt: .white, orderIndex: 4,
             title: "Marco", description: "",
             tags: [], isLocked: true, isCompleted: false,
             kind: .characterMoment,
             questions: [],
             characterMoment: CharacterMomentData(
                 character: .marco,
                 message: "La guardia cerrada es un sistema, no solo una posición. No estás esperando — estás cazando. Cada segundo que están en tu guardia, buscas la apertura."
             )),

        Unit(id: "wb-03-l1", belt: .white, orderIndex: 5,
             title: "Pase de Guardia", description: "Rompe y pasa la guardia cerrada",
             tags: ["guard", "passing"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(paseGuardiaPreguntas[0..<4]),
             coachIntro: "Pasar la guardia requiere paciencia. Mantén los codos pegados, controla sus caderas.",
             topicTitle: "Pase de Guardia",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-03-l2", belt: .white, orderIndex: 6,
             title: "Pase de Guardia", description: "Rompe y pasa la guardia cerrada",
             tags: ["guard", "passing"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(paseGuardiaPreguntas[4..<8]),
             topicTitle: "Pase de Guardia",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-mr-gg", belt: .white, orderIndex: 7,
             title: "Repaso: Juego de Guardia", description: "Preguntas mezcladas de todos los temas de guardia",
             tags: ["guard"], isLocked: true, isCompleted: false,
             kind: .mixedReview,
             questions: [
                 guardiaCerradaControlPreguntas[0], guardiaCerradaControlPreguntas[4],
                 guardiaCerradaAtaquesPreguntas[0], guardiaCerradaAtaquesPreguntas[4],
                 paseGuardiaPreguntas[0], paseGuardiaPreguntas[4],
             ]),

        Unit(id: "wb-me-gg", belt: .white, orderIndex: 8,
             title: "Examen: Juego de Guardia", description: "Demuestra tu juego de guardia",
             tags: ["guard"], isLocked: true, isCompleted: false,
             kind: .miniExam,
             questions: [
                 guardiaCerradaControlPreguntas[1], guardiaCerradaControlPreguntas[5],
                 guardiaCerradaAtaquesPreguntas[1], guardiaCerradaAtaquesPreguntas[5],
                 paseGuardiaPreguntas[1], paseGuardiaPreguntas[5],
                 guardiaCerradaControlPreguntas[2], guardiaCerradaAtaquesPreguntas[2],
             ]),

        // ── JUEGO SUPERIOR ─────────────────────────────────────────────────

        Unit(id: "wb-04-l1", belt: .white, orderIndex: 9,
             title: "Control Lateral Superior", description: "Mantén y domina",
             tags: ["side control"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(controlLateralSuperiorPreguntas[0..<4]),
             coachIntro: "El control lateral trata de peso y ángulos. Caderas bajas, cross-face activo.",
             sectionTitle: "Juego Superior",
             topicTitle: "Control Lateral Superior",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-04-l2", belt: .white, orderIndex: 10,
             title: "Control Lateral Superior", description: "Mantén y domina",
             tags: ["side control"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(controlLateralSuperiorPreguntas[4..<8]),
             topicTitle: "Control Lateral Superior",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-05-l1", belt: .white, orderIndex: 11,
             title: "Escapar el Control Lateral", description: "Recupera la guardia",
             tags: ["side control", "escapes"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(escaparControlLateralPreguntas[0..<4]),
             coachIntro: "Escapar el control lateral empieza con marcos — crea espacio antes de moverte.",
             topicTitle: "Escapar el Control Lateral",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-05-l2", belt: .white, orderIndex: 12,
             title: "Escapar el Control Lateral", description: "Recupera la guardia",
             tags: ["side control", "escapes"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(escaparControlLateralPreguntas[4..<8]),
             topicTitle: "Escapar el Control Lateral",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-cm-02", belt: .white, orderIndex: 13,
             title: "Old Chen", description: "",
             tags: [], isLocked: true, isCompleted: false,
             kind: .characterMoment,
             questions: [],
             characterMoment: CharacterMomentData(
                 character: .oldChen,
                 message: "Te moviste antes de estar listo. El escape empieza antes de lo que crees."
             )),

        Unit(id: "wb-06-l1", belt: .white, orderIndex: 14,
             title: "Control desde Montada", description: "Mantén y avanza desde la montada",
             tags: ["mount"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(controlMontadaPreguntas[0..<4]),
             coachIntro: "La montada es tu posición de mayor valor. Caderas bajas, cross-face, sigue sus escapes.",
             topicTitle: "Control desde Montada",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-06-l2", belt: .white, orderIndex: 15,
             title: "Control desde Montada", description: "Mantén y avanza desde la montada",
             tags: ["mount"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(controlMontadaPreguntas[4..<8]),
             topicTitle: "Control desde Montada",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-07-l1", belt: .white, orderIndex: 16,
             title: "Escapar la Montada", description: "Escapa desde abajo de la montada",
             tags: ["mount", "escapes"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(escaparMontadaPreguntas[0..<4]),
             coachIntro: "Dos herramientas: upa (puente y roleo) y codo-rodilla. Aprende cuándo usar cada una.",
             topicTitle: "Escapar la Montada",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-07-l2", belt: .white, orderIndex: 17,
             title: "Escapar la Montada", description: "Escapa desde abajo de la montada",
             tags: ["mount", "escapes"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(escaparMontadaPreguntas[4..<8]),
             topicTitle: "Escapar la Montada",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-cm-03", belt: .white, orderIndex: 18,
             title: "Rex", description: "",
             tags: [], isLocked: true, isCompleted: false,
             kind: .characterMoment,
             questions: [],
             characterMoment: CharacterMomentData(
                 character: .rex,
                 message: "Oye oye oye — el escape de montada es donde yo siempre intento usar la fuerza y Marco me mira con resignación. ¡Pero tú sí lo lograste! CRACK."
             )),

        Unit(id: "wb-mr-tg", belt: .white, orderIndex: 19,
             title: "Repaso: Juego Superior", description: "Preguntas mezcladas del juego superior",
             tags: [], isLocked: true, isCompleted: false,
             kind: .mixedReview,
             questions: [
                 controlLateralSuperiorPreguntas[0], controlLateralSuperiorPreguntas[4],
                 escaparControlLateralPreguntas[0], escaparControlLateralPreguntas[4],
                 controlMontadaPreguntas[0], controlMontadaPreguntas[4],
                 escaparMontadaPreguntas[0], escaparMontadaPreguntas[4],
             ]),

        Unit(id: "wb-me-tg", belt: .white, orderIndex: 20,
             title: "Examen: Juego Superior", description: "Demuestra tu juego superior",
             tags: [], isLocked: true, isCompleted: false,
             kind: .miniExam,
             questions: [
                 controlLateralSuperiorPreguntas[1], controlLateralSuperiorPreguntas[5],
                 escaparControlLateralPreguntas[1], escaparControlLateralPreguntas[5],
                 controlMontadaPreguntas[1], controlMontadaPreguntas[5],
                 escaparMontadaPreguntas[1], escaparMontadaPreguntas[5],
             ]),

        // ── ESPALDA Y SUMISIONES ───────────────────────────────────────────

        Unit(id: "wb-08-l1", belt: .white, orderIndex: 21,
             title: "Control de Espalda", description: "Toma y mantén la espalda",
             tags: ["back control"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(controlEspaldaPreguntas[0..<4]),
             coachIntro: "La espalda es la posición más dominante. Ganchos adentro, cinturón apretado.",
             sectionTitle: "Espalda y Sumisiones",
             topicTitle: "Control de Espalda",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-08-l2", belt: .white, orderIndex: 22,
             title: "Control de Espalda", description: "Toma y mantén la espalda",
             tags: ["back control"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(controlEspaldaPreguntas[4..<8]),
             topicTitle: "Control de Espalda",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-09-l1", belt: .white, orderIndex: 23,
             title: "Sumisiones", description: "Sumisiones básicas",
             tags: ["submissions"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(sumisionesPreguntas[0..<4]),
             coachIntro: "Las sumisiones solo funcionan desde posiciones controladas. Posición primero, luego sumisión.",
             topicTitle: "Sumisiones",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-09-l2", belt: .white, orderIndex: 24,
             title: "Sumisiones", description: "Sumisiones básicas",
             tags: ["submissions"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(sumisionesPreguntas[4..<8]),
             topicTitle: "Sumisiones",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-cm-04", belt: .white, orderIndex: 25,
             title: "Old Chen", description: "",
             tags: [], isLocked: true, isCompleted: false,
             kind: .characterMoment,
             questions: [],
             characterMoment: CharacterMomentData(
                 character: .oldChen,
                 message: "La sumisión es el punto final. La oración es la posición. Aprende a escribir la oración."
             )),

        Unit(id: "wb-10-l1", belt: .white, orderIndex: 26,
             title: "Derribos", description: "Lleva la pelea al suelo",
             tags: ["takedowns"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(derribosPreguntas[0..<4]),
             coachIntro: "Dos shots primero: doble pierna y pierna simple. Cambio de nivel, paso de penetración, empuja.",
             topicTitle: "Derribos",
             lessonIndex: 1, lessonTotal: 2),

        Unit(id: "wb-10-l2", belt: .white, orderIndex: 27,
             title: "Derribos", description: "Lleva la pelea al suelo",
             tags: ["takedowns"], isLocked: true, isCompleted: false,
             kind: .lesson,
             questions: Array(derribosPreguntas[4..<8]),
             topicTitle: "Derribos",
             lessonIndex: 2, lessonTotal: 2),

        Unit(id: "wb-mr-bs", belt: .white, orderIndex: 28,
             title: "Repaso: Espalda y Sumisiones", description: "",
             tags: [], isLocked: true, isCompleted: false,
             kind: .mixedReview,
             questions: [
                 controlEspaldaPreguntas[0], controlEspaldaPreguntas[4],
                 sumisionesPreguntas[0], sumisionesPreguntas[4],
                 derribosPreguntas[0], derribosPreguntas[4],
             ]),

        Unit(id: "wb-me-bs", belt: .white, orderIndex: 29,
             title: "Examen: Espalda y Sumisiones", description: "",
             tags: [], isLocked: true, isCompleted: false,
             kind: .miniExam,
             questions: [
                 controlEspaldaPreguntas[1], controlEspaldaPreguntas[5],
                 sumisionesPreguntas[1], sumisionesPreguntas[5],
                 derribosPreguntas[1], derribosPreguntas[5],
                 controlEspaldaPreguntas[2], sumisionesPreguntas[2],
             ]),

        // ── EXAMEN DE FRANJA ───────────────────────────────────────────────

        Unit(id: "wb-bt1", belt: .white, orderIndex: 30,
             title: "Examen Franja 1", description: "Demuestra tus fundamentos del Cinturón Blanco",
             tags: [], isLocked: true, isCompleted: false,
             kind: .beltTest,
             questions: examenFranjaPreguntasES,
             sectionTitle: "Examen de Franja"),
    ]
}
