import Foundation

// MARK: - Questions per Unit

private let closedGuardQuestions: [Question] = [
    Question(id: "q-cg-01", unitId: "wb-01", format: .mcq2,
             prompt: "Your opponent tries to stand up from your closed guard. What should you do?",
             options: ["Break their posture down", "Open guard immediately"],
             correctAnswer: "Break their posture down",
             explanation: "Pull them forward to break posture before they base out and pass.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-02", unitId: "wb-01", format: .mcq4,
             prompt: "Which grip best breaks your opponent's posture in closed guard?",
             options: ["Collar and sleeve", "Double collar", "Double underhooks on head", "Wrist control"],
             correctAnswer: "Double collar",
             explanation: "Double collar grips let you pull the head down and break posture efficiently.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-03", unitId: "wb-01", format: .trueFalse,
             prompt: "Squeezing your knees together in closed guard gives you more control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Closed knees remove space for your opponent to posture up.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-04", unitId: "wb-01", format: .mcq4,
             prompt: "What is the PRIMARY goal of closed guard?",
             options: ["Defend and stall", "Wait for your opponent to tire", "Control distance and threaten attacks", "Rest your legs"],
             correctAnswer: "Control distance and threaten attacks",
             explanation: "Closed guard is an offensive position — break posture, attack submissions, set up sweeps.",
             tags: ["guard"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-cg-05", unitId: "wb-01", format: .trueFalse,
             prompt: "You should keep your guard closed when your opponent stands up completely.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Holding closed guard while they stand risks a guard pass. Open and adapt.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-cg-06", unitId: "wb-01", format: .mcq2,
             prompt: "Your opponent posts both hands on your hips to create distance. Best response?",
             options: ["Pull their elbows in and break posture", "Open guard and scoot away"],
             correctAnswer: "Pull their elbows in and break posture",
             explanation: "Removing their base by collapsing the elbows shuts down the posture attempt.",
             tags: ["guard"], difficulty: 2, sceneImageName: nil),
]

private let guardEscapeQuestions: [Question] = [
    Question(id: "q-ge-01", unitId: "wb-02", format: .mcq4,
             prompt: "When passing closed guard from knees, where should your elbows be?",
             options: ["Wide for balance", "On the mat beside you", "Tight to their hips", "Grabbing their belt"],
             correctAnswer: "Tight to their hips",
             explanation: "Tight elbows prevent the opponent from getting underhooks or arm drags.",
             tags: ["guard", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-ge-02", unitId: "wb-02", format: .trueFalse,
             prompt: "Standing up is always the safest way to pass closed guard.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Standing can be effective but is risky — sweeps and leg locks become available.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-03", unitId: "wb-02", format: .mcq2,
             prompt: "Your opponent attempts a hip bump sweep from closed guard. What stops it?",
             options: ["Post your hand on the mat behind you", "Squeeze your knees tighter"],
             correctAnswer: "Post your hand on the mat behind you",
             explanation: "A hand post behind you removes the base they need to complete the sweep.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-04", unitId: "wb-02", format: .mcq4,
             prompt: "Which is NOT a valid technique to open closed guard?",
             options: ["Stand and drive knee to tailbone", "Elbow to knee pressure", "Grab one ankle and push", "Grab their belt and pull up"],
             correctAnswer: "Grab their belt and pull up",
             explanation: "Grabbing the belt doesn't create the hip pressure needed to open the guard.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-05", unitId: "wb-02", format: .trueFalse,
             prompt: "When passing guard, getting one knee free is enough — you don't need to control both hips.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Controlling both hips prevents the guard from re-closing and limits sweep attempts.",
             tags: ["guard", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-ge-06", unitId: "wb-02", format: .mcq2,
             prompt: "You are about to pass the guard. Your opponent grabs your sleeve. Priority?",
             options: ["Clear the grip before passing", "Ignore it and rush the pass"],
             correctAnswer: "Clear the grip before passing",
             explanation: "Uncleared grips give your opponent handles to re-guard or sweep mid-pass.",
             tags: ["guard", "escapes"], difficulty: 3, sceneImageName: nil),
]

private let sideControlQuestions: [Question] = [
    Question(id: "q-sc-01", unitId: "wb-03", format: .mcq4,
             prompt: "In side control, where should your hips be to apply maximum pressure?",
             options: ["High and away from opponent", "Low and heavy across their torso", "Perpendicular at their waist", "Stacked on their legs"],
             correctAnswer: "Low and heavy across their torso",
             explanation: "Low hips add pressure and make it hard for the opponent to bridge or roll.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sc-02", unitId: "wb-03", format: .trueFalse,
             prompt: "Cross-face pressure in side control helps flatten your opponent.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Cross-face turns the head and disconnects the opponent's hip-shoulder alignment.",
             tags: ["side control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sc-03", unitId: "wb-03", format: .mcq2,
             prompt: "Your opponent tries to escape side control by pushing your head. Best response?",
             options: ["Swim under their arm for underhook", "Back away and re-establish"],
             correctAnswer: "Swim under their arm for underhook",
             explanation: "Swimming under creates underhook control and maintains the position.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-04", unitId: "wb-03", format: .mcq4,
             prompt: "Which submission is most directly available from standard side control?",
             options: ["Rear naked choke", "Heel hook", "Kimura on the near arm", "Triangle from guard"],
             correctAnswer: "Kimura on the near arm",
             explanation: "Kimura is directly available from side control when the opponent's arm is exposed.",
             tags: ["side control", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-05", unitId: "wb-03", format: .trueFalse,
             prompt: "The 'north-south' position is a variant of side control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "North-south is side control rotated 180° — head near opponent's hips.",
             tags: ["side control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sc-06", unitId: "wb-03", format: .mcq2,
             prompt: "Your opponent bridges strongly to escape side control. To counter, you should:",
             options: ["Go with the roll and take mount", "Post your leg out and stay flat"],
             correctAnswer: "Go with the roll and take mount",
             explanation: "Following the bridge and taking mount is the reward for reading the escape.",
             tags: ["side control"], difficulty: 3, sceneImageName: nil),
]

private let mountQuestions: [Question] = [
    Question(id: "q-mt-01", unitId: "wb-04", format: .mcq4,
             prompt: "Your opponent bridges (upa) to escape mount. What is the best counter?",
             options: ["Squeeze your knees tighter", "Post your arm out to base and go with it", "Lean forward with all weight", "Grab their collar"],
             correctAnswer: "Post your arm out to base and go with it",
             explanation: "Posting stops the bridge. Following the roll lets you take mount from the other side.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mt-02", unitId: "wb-04", format: .trueFalse,
             prompt: "High mount (near the armpits) gives you better control than low mount.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "High mount limits arm movement and opens more submission opportunities.",
             tags: ["mount"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mt-03", unitId: "wb-04", format: .mcq2,
             prompt: "Which mount escape uses a bridge and rotation to roll the top person over?",
             options: ["Upa escape", "Elbow-knee escape"],
             correctAnswer: "Upa escape",
             explanation: "Upa uses bridging force and a trap on the arm/leg to roll.",
             tags: ["mount", "escapes"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-mt-04", unitId: "wb-04", format: .mcq4,
             prompt: "The elbow-knee escape from mount is designed to:",
             options: ["Submit the opponent with a triangle", "Roll them over your head", "Recover half guard or full guard", "Take their back"],
             correctAnswer: "Recover half guard or full guard",
             explanation: "Elbow-knee escape shrimps to create space and re-guard.",
             tags: ["mount", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-mt-05", unitId: "wb-04", format: .trueFalse,
             prompt: "In mount, keeping your heels hooked under your opponent's legs makes it harder for them to escape.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Hooks under the legs limit bridging power and prevent the elbow-knee escape.",
             tags: ["mount"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-mt-06", unitId: "wb-04", format: .mcq2,
             prompt: "Your opponent gets their elbow to their knee and starts shrimping. You should:",
             options: ["Follow their hips and re-establish mount", "Abandon mount and go to side control"],
             correctAnswer: "Follow their hips and re-establish mount",
             explanation: "Staying active and following the hips is the key to keeping mount.",
             tags: ["mount"], difficulty: 3, sceneImageName: nil),
]

private let backControlQuestions: [Question] = [
    Question(id: "q-bc-01", unitId: "wb-05", format: .mcq4,
             prompt: "When you have back control, where should your hooks be?",
             options: ["Behind their knees", "On their ankles", "Inside their thighs", "Outside their hips"],
             correctAnswer: "Inside their thighs",
             explanation: "Inside hooks on the thighs keep you attached and limit hip mobility.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-02", unitId: "wb-05", format: .trueFalse,
             prompt: "You must maintain at least one hook to keep back control.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Losing both hooks lets the opponent escape or roll out of back control.",
             tags: ["back control"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-bc-03", unitId: "wb-05", format: .mcq2,
             prompt: "When setting up the rear naked choke, what must you establish first?",
             options: ["Seatbelt grip (over-under around torso)", "Choking arm directly under chin"],
             correctAnswer: "Seatbelt grip (over-under around torso)",
             explanation: "Seatbelt control establishes position and prevents the opponent turning.",
             tags: ["back control", "submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-04", unitId: "wb-05", format: .mcq4,
             prompt: "To escape back control, which direction should you move toward?",
             options: ["Away from both arms", "Toward the choking arm side", "Straight forward", "Toward the non-choking arm side"],
             correctAnswer: "Toward the choking arm side",
             explanation: "Moving toward the choking arm side lets you work to face the opponent.",
             tags: ["back control", "escapes"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-05", unitId: "wb-05", format: .trueFalse,
             prompt: "A body triangle is a stronger control than two hooks from back position.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "The body triangle locks the hips completely and is very hard to escape.",
             tags: ["back control"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-bc-06", unitId: "wb-05", format: .mcq2,
             prompt: "Your opponent grabs your choking wrist to defend the RNC. You should:",
             options: ["Switch to a bow-and-arrow or collar choke", "Keep pulling the same arm harder"],
             correctAnswer: "Switch to a bow-and-arrow or collar choke",
             explanation: "Switching attacks prevents stalling and exploits their defensive focus.",
             tags: ["back control", "submissions"], difficulty: 3, sceneImageName: nil),
]

private let submissionQuestions: [Question] = [
    Question(id: "q-sub-01", unitId: "wb-06", format: .mcq4,
             prompt: "When applying an armbar from mount, the correct position is:",
             options: ["Thumbs down, pull to chest", "Both hands on the wrist, push away", "Thumbs up, hips thrust up", "Wrists crossed, pull down"],
             correctAnswer: "Thumbs up, hips thrust up",
             explanation: "Thumb up rotates the elbow into position. Hips thrust apply the extension force.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sub-02", unitId: "wb-06", format: .trueFalse,
             prompt: "A triangle choke works by compressing the carotid arteries, not the airway.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Blood chokes cut off blood to the brain — faster and more effective than air chokes.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-03", unitId: "wb-06", format: .mcq2,
             prompt: "The kimura grip is: one hand on their wrist, the other hand...",
             options: ["Gripping your own wrist (figure-four)", "On their bicep"],
             correctAnswer: "Gripping your own wrist (figure-four)",
             explanation: "Kimura = figure-four: wrist with one hand, grip your own wrist with the other.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sub-04", unitId: "wb-06", format: .mcq4,
             prompt: "When is it appropriate to tap in training?",
             options: ["Only when you are about to be knocked out", "Only if you have no way to escape", "Whenever a submission is applied and you feel it working", "Never — tapping is giving up"],
             correctAnswer: "Whenever a submission is applied and you feel it working",
             explanation: "Tapping early protects you from injury and is a sign of good training culture.",
             tags: ["submissions"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-sub-05", unitId: "wb-06", format: .trueFalse,
             prompt: "The rear naked choke requires you to lock your hands together to be effective.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "The RNC uses a 'rear naked' (no gi) grip — one arm chokes, the other applies pressure on the head.",
             tags: ["submissions"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-sub-06", unitId: "wb-06", format: .mcq2,
             prompt: "You have an armbar but your opponent is clasping their hands to defend. Best response?",
             options: ["Break their grip by extending one arm and rotating", "Pull both arms toward you simultaneously"],
             correctAnswer: "Break their grip by extending one arm and rotating",
             explanation: "Rotating one arm breaks the grip structure more efficiently than pulling straight.",
             tags: ["submissions"], difficulty: 3, sceneImageName: nil),
]

private let takedownQuestions: [Question] = [
    Question(id: "q-td-01", unitId: "wb-07", format: .mcq4,
             prompt: "In a single-leg takedown, the key finish movement after securing the leg is:",
             options: ["Pull straight back", "Run the pipe (step outside and cut)", "Jump on top", "Lift straight up"],
             correctAnswer: "Run the pipe (step outside and cut)",
             explanation: "Stepping outside cuts the angle and drops your weight through the leg.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-02", unitId: "wb-07", format: .trueFalse,
             prompt: "In wrestling, a 'sprawl' is used to defend against a double-leg shot.",
             options: ["True", "False"],
             correctAnswer: "True",
             explanation: "Sprawling drives your hips back and down to stuff the shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-td-03", unitId: "wb-07", format: .mcq2,
             prompt: "The double-leg takedown requires you to:",
             options: ["Change levels and shoot low", "Stay tall and grab both wrists"],
             correctAnswer: "Change levels and shoot low",
             explanation: "Level change drops below the opponent's center of gravity for the shot.",
             tags: ["takedowns"], difficulty: 1, sceneImageName: nil),
    Question(id: "q-td-04", unitId: "wb-07", format: .mcq4,
             prompt: "After a successful takedown, your immediate priority is:",
             options: ["Go for a submission immediately", "Stand back up", "Establish top position control", "Call for a time-out"],
             correctAnswer: "Establish top position control",
             explanation: "Secure position first — rushing submissions from bad position loses them.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-05", unitId: "wb-07", format: .trueFalse,
             prompt: "Pulling guard counts as a takedown in competition BJJ.",
             options: ["True", "False"],
             correctAnswer: "False",
             explanation: "Pulling guard gives up the takedown points (2 pts) to the opponent.",
             tags: ["takedowns"], difficulty: 2, sceneImageName: nil),
    Question(id: "q-td-06", unitId: "wb-07", format: .mcq2,
             prompt: "Your opponent has a collar-and-elbow grip on you in standup. You want to shoot. First:",
             options: ["Break their grips before shooting", "Shoot immediately before they react"],
             correctAnswer: "Break their grips before shooting",
             explanation: "Shooting with their grips intact lets them sprawl or redirect your momentum.",
             tags: ["takedowns"], difficulty: 3, sceneImageName: nil),
]

// Belt test uses a shuffled pool drawn from all units
private let beltTestQuestions: [Question] = {
    let all = closedGuardQuestions + guardEscapeQuestions + sideControlQuestions
        + mountQuestions + backControlQuestions + submissionQuestions + takedownQuestions
    return all.map { q in
        Question(id: "bt-\(q.id)", unitId: "wb-bt1",
                 format: q.format, prompt: q.prompt,
                 options: q.options, correctAnswer: q.correctAnswer,
                 explanation: q.explanation, tags: q.tags,
                 difficulty: q.difficulty, sceneImageName: nil)
    }
}()

// MARK: - Units

extension Unit {
    static let whitebelt_en: [Unit] = [
        Unit(id: "wb-01", belt: .white, orderIndex: 0,
             title: "Closed Guard", description: "Basics of closed guard control",
             tags: ["guard"], isLocked: false, isCompleted: false, isBeltTest: false,
             questions: closedGuardQuestions),
        Unit(id: "wb-02", belt: .white, orderIndex: 1,
             title: "Guard Escape", description: "Escaping from closed guard",
             tags: ["escapes", "guard"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: guardEscapeQuestions),
        Unit(id: "wb-03", belt: .white, orderIndex: 2,
             title: "Side Control", description: "Maintaining side control",
             tags: ["side control"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: sideControlQuestions),
        Unit(id: "wb-04", belt: .white, orderIndex: 3,
             title: "Mount", description: "Mount position and control",
             tags: ["mount"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: mountQuestions),
        Unit(id: "wb-05", belt: .white, orderIndex: 4,
             title: "Back Control", description: "Taking and keeping the back",
             tags: ["back control"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: backControlQuestions),
        Unit(id: "wb-06", belt: .white, orderIndex: 5,
             title: "Submissions", description: "Basic submissions from dominant positions",
             tags: ["submissions"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: submissionQuestions),
        Unit(id: "wb-07", belt: .white, orderIndex: 6,
             title: "Takedowns", description: "Getting the fight to the ground",
             tags: ["takedowns"], isLocked: true, isCompleted: false, isBeltTest: false,
             questions: takedownQuestions),
        Unit(id: "wb-bt1", belt: .white, orderIndex: 7,
             title: "Stripe 1 Test", description: "Prove your White Belt foundations",
             tags: [], isLocked: true, isCompleted: false, isBeltTest: true,
             questions: beltTestQuestions),
    ]
}
